import { draftQuoteEmail, type StorageAdapter } from '@pkg/core';
import type { Db } from '@pkg/db';
import { renderQuoteDocumentPdf } from '@pkg/pdf';
import type { AuthId, QuoteDraftEmailInput, QuoteDraftEmailResult } from '@pkg/schema';

import { emailSender } from '@/email/index.js';

/**
 * Wires the API-side transports (PDF renderer, email sender) around the core draft-quote-email flow so
 * the tRPC route and the AI write tool deliver drafts the same way. Callers supply the email body they
 * have already resolved — generated by the assistant for the route, authored by the model for the tool.
 */
export function deliverQuoteDraftEmail({
  actorUserId,
  db,
  emailBody,
  input,
  recipientEmail,
  storage,
}: {
  actorUserId: AuthId;
  db: Db;
  emailBody: string;
  input: QuoteDraftEmailInput;
  recipientEmail: string;
  storage: StorageAdapter;
}): Promise<QuoteDraftEmailResult> {
  return draftQuoteEmail({
    actorUserId,
    db,
    emailBody,
    input,
    pdfRenderer: renderQuoteDocumentPdf,
    recipientEmail,
    sendEmail: (message) =>
      emailSender.send({
        attachments: message.attachments,
        html: message.html,
        subject: message.subject,
        text: message.text,
        to: message.to,
        type: 'quote-draft',
      }),
    storage,
  });
}
