/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from '../routes/__root'
import { Route as IndexRouteImport } from '../routes/index'
import { Route as AuthedRouteImport } from '../routes/_authed'
import { Route as ForgotPasswordRouteImport } from '../routes/forgot-password'
import { Route as LoginRouteImport } from '../routes/login'
import { Route as PrivacyRouteImport } from '../routes/privacy'
import { Route as ResetPasswordRouteImport } from '../routes/reset-password'
import { Route as SupportRouteImport } from '../routes/support'
import { Route as VerifyEmailRouteImport } from '../routes/verify-email'
import { Route as AuthedContractingRouteImport } from '../routes/_authed.contracting'
import { Route as AuthedEquipmentRouteImport } from '../routes/_authed.equipment'
import { Route as AuthedContractingIndexRouteImport } from '../routes/_authed.contracting.index'
import { Route as AuthedEquipmentAuditRouteImport } from '../routes/_authed.equipment.audit'
import { Route as AuthedEquipmentBaysRouteImport } from '../routes/_authed.equipment.bays'
import { Route as AuthedEquipmentCatalogTranslationsRouteImport } from '../routes/_authed.equipment.catalog-translations'
import { Route as AuthedEquipmentCustomersRouteImport } from '../routes/_authed.equipment.customers'
import { Route as AuthedEquipmentDashboardRouteImport } from '../routes/_authed.equipment.dashboard'
import { Route as AuthedEquipmentFeedbackRouteImport } from '../routes/_authed.equipment.feedback'
import { Route as AuthedEquipmentInventoryRouteImport } from '../routes/_authed.equipment.inventory'
import { Route as AuthedEquipmentJobsRouteImport } from '../routes/_authed.equipment.jobs'
import { Route as AuthedEquipmentPartsRouteImport } from '../routes/_authed.equipment.parts'
import { Route as AuthedEquipmentProductRangesRouteImport } from '../routes/_authed.equipment.product-ranges'
import { Route as AuthedEquipmentProductsRouteImport } from '../routes/_authed.equipment.products'
import { Route as AuthedEquipmentPurchaseOrdersRouteImport } from '../routes/_authed.equipment.purchase-orders'
import { Route as AuthedEquipmentQuotesRouteImport } from '../routes/_authed.equipment.quotes'
import { Route as AuthedEquipmentSuppliersRouteImport } from '../routes/_authed.equipment.suppliers'
import { Route as AuthedEquipmentUnitsRouteImport } from '../routes/_authed.equipment.units'
import { Route as AuthedEquipmentUsersRouteImport } from '../routes/_authed.equipment.users'
import { Route as AuthedEquipmentCustomersIndexRouteImport } from '../routes/_authed.equipment.customers.index'
import { Route as AuthedEquipmentInventoryIndexRouteImport } from '../routes/_authed.equipment.inventory.index'
import { Route as AuthedEquipmentInventoryPartIdRouteImport } from '../routes/_authed.equipment.inventory.$partId'
import { Route as AuthedEquipmentInventoryBuyListRouteImport } from '../routes/_authed.equipment.inventory.buy-list'
import { Route as AuthedEquipmentInventoryCloseOutRouteImport } from '../routes/_authed.equipment.inventory.close-out'
import { Route as AuthedEquipmentInventoryPriceVarianceRouteImport } from '../routes/_authed.equipment.inventory.price-variance'
import { Route as AuthedEquipmentInventoryStocktakeRouteImport } from '../routes/_authed.equipment.inventory.stocktake'
import { Route as AuthedEquipmentJobsIndexRouteImport } from '../routes/_authed.equipment.jobs.index'
import { Route as AuthedEquipmentJobsIdRouteImport } from '../routes/_authed.equipment.jobs.$id'
import { Route as AuthedEquipmentJobsActivityRouteImport } from '../routes/_authed.equipment.jobs.activity'
import { Route as AuthedEquipmentJobsCalendarRouteImport } from '../routes/_authed.equipment.jobs.calendar'
import { Route as AuthedEquipmentJobsListRouteImport } from '../routes/_authed.equipment.jobs.list'
import { Route as AuthedEquipmentJobsStockBuildRouteImport } from '../routes/_authed.equipment.jobs.stock-build'
import { Route as AuthedEquipmentProductRangesIndexRouteImport } from '../routes/_authed.equipment.product-ranges.index'
import { Route as AuthedEquipmentProductsIndexRouteImport } from '../routes/_authed.equipment.products.index'
import { Route as AuthedEquipmentPurchaseOrdersIndexRouteImport } from '../routes/_authed.equipment.purchase-orders.index'
import { Route as AuthedEquipmentPurchaseOrdersIdRouteImport } from '../routes/_authed.equipment.purchase-orders.$id'
import { Route as AuthedEquipmentQuotesIndexRouteImport } from '../routes/_authed.equipment.quotes.index'
import { Route as AuthedEquipmentSuppliersIndexRouteImport } from '../routes/_authed.equipment.suppliers.index'
import { Route as AuthedEquipmentUnitsIndexRouteImport } from '../routes/_authed.equipment.units.index'
import { Route as AuthedEquipmentUnitsIdRouteImport } from '../routes/_authed.equipment.units.$id'
import { Route as AuthedEquipmentCustomersIdEditRouteImport } from '../routes/_authed.equipment.customers.$id.edit'
import { Route as AuthedEquipmentInventoryCloseOutIndexRouteImport } from '../routes/_authed.equipment.inventory.close-out.index'
import { Route as AuthedEquipmentInventoryCloseOutJobIdRouteImport } from '../routes/_authed.equipment.inventory.close-out.$jobId'
import { Route as AuthedEquipmentInventoryJobVarianceJobIdRouteImport } from '../routes/_authed.equipment.inventory.job-variance.$jobId'
import { Route as AuthedEquipmentInventoryStocktakeIndexRouteImport } from '../routes/_authed.equipment.inventory.stocktake.index'
import { Route as AuthedEquipmentInventoryStocktakeSessionIdRouteImport } from '../routes/_authed.equipment.inventory.stocktake.$sessionId'
import { Route as AuthedEquipmentProductRangesIdEditRouteImport } from '../routes/_authed.equipment.product-ranges.$id.edit'
import { Route as AuthedEquipmentProductsIdEditRouteImport } from '../routes/_authed.equipment.products.$id.edit'
import { Route as AuthedEquipmentQuotesIdEditRouteImport } from '../routes/_authed.equipment.quotes.$id_.edit'
import { Route as AuthedEquipmentQuotesIdStartJobRouteImport } from '../routes/_authed.equipment.quotes.$id_.start-job'
import { Route as AuthedEquipmentSuppliersIdEditRouteImport } from '../routes/_authed.equipment.suppliers.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedContractingRoute = AuthedContractingRouteImport.update({
  id: '/contracting',
  path: '/contracting',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEquipmentRoute = AuthedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContractingIndexRoute = AuthedContractingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedContractingRoute,
} as any)
const AuthedEquipmentAuditRoute = AuthedEquipmentAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedEquipmentRoute,
} as any)
const AuthedEquipmentBaysRoute = AuthedEquipmentBaysRouteImport.update({
  id: '/bays',
  path: '/bays',
  getParentRoute: () => AuthedEquipmentRoute,
} as any)
const AuthedEquipmentCatalogTranslationsRoute =
  AuthedEquipmentCatalogTranslationsRouteImport.update({
    id: '/catalog-translations',
    path: '/catalog-translations',
    getParentRoute: () => AuthedEquipmentRoute,
  } as any)
const AuthedEquipmentCustomersRoute =
  AuthedEquipmentCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthedEquipmentRoute,
  } as any)
const AuthedEquipmentDashboardRoute =
  AuthedEquipmentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedEquipmentRoute,
  } as any)
const AuthedEquipmentFeedbackRoute = AuthedEquipmentFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthedEquipmentRoute,
} as any)
const AuthedEquipmentInventoryRoute =
  AuthedEquipmentInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthedEquipmentRoute,
  } as any)
const AuthedEquipmentJobsRoute = AuthedEquipmentJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthedEquipmentRoute,
} as any)
const AuthedEquipmentPartsRoute = AuthedEquipmentPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthedEquipmentRoute,
} as any)
const AuthedEquipmentProductRangesRoute =
  AuthedEquipmentProductRangesRouteImport.update({
    id: '/product-ranges',
    path: '/product-ranges',
    getParentRoute: () => AuthedEquipmentRoute,
  } as any)
const AuthedEquipmentProductsRoute = AuthedEquipmentProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedEquipmentRoute,
} as any)
const AuthedEquipmentPurchaseOrdersRoute =
  AuthedEquipmentPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthedEquipmentRoute,
  } as any)
const AuthedEquipmentQuotesRoute = AuthedEquipmentQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthedEquipmentRoute,
} as any)
const AuthedEquipmentSuppliersRoute =
  AuthedEquipmentSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthedEquipmentRoute,
  } as any)
const AuthedEquipmentUnitsRoute = AuthedEquipmentUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthedEquipmentRoute,
} as any)
const AuthedEquipmentUsersRoute = AuthedEquipmentUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedEquipmentRoute,
} as any)
const AuthedEquipmentCustomersIndexRoute =
  AuthedEquipmentCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentCustomersRoute,
  } as any)
const AuthedEquipmentInventoryIndexRoute =
  AuthedEquipmentInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentInventoryRoute,
  } as any)
const AuthedEquipmentInventoryPartIdRoute =
  AuthedEquipmentInventoryPartIdRouteImport.update({
    id: '/$partId',
    path: '/$partId',
    getParentRoute: () => AuthedEquipmentInventoryRoute,
  } as any)
const AuthedEquipmentInventoryBuyListRoute =
  AuthedEquipmentInventoryBuyListRouteImport.update({
    id: '/buy-list',
    path: '/buy-list',
    getParentRoute: () => AuthedEquipmentInventoryRoute,
  } as any)
const AuthedEquipmentInventoryCloseOutRoute =
  AuthedEquipmentInventoryCloseOutRouteImport.update({
    id: '/close-out',
    path: '/close-out',
    getParentRoute: () => AuthedEquipmentInventoryRoute,
  } as any)
const AuthedEquipmentInventoryPriceVarianceRoute =
  AuthedEquipmentInventoryPriceVarianceRouteImport.update({
    id: '/price-variance',
    path: '/price-variance',
    getParentRoute: () => AuthedEquipmentInventoryRoute,
  } as any)
const AuthedEquipmentInventoryStocktakeRoute =
  AuthedEquipmentInventoryStocktakeRouteImport.update({
    id: '/stocktake',
    path: '/stocktake',
    getParentRoute: () => AuthedEquipmentInventoryRoute,
  } as any)
const AuthedEquipmentJobsIndexRoute =
  AuthedEquipmentJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentJobsRoute,
  } as any)
const AuthedEquipmentJobsIdRoute = AuthedEquipmentJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedEquipmentJobsRoute,
} as any)
const AuthedEquipmentJobsActivityRoute =
  AuthedEquipmentJobsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthedEquipmentJobsRoute,
  } as any)
const AuthedEquipmentJobsCalendarRoute =
  AuthedEquipmentJobsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthedEquipmentJobsRoute,
  } as any)
const AuthedEquipmentJobsListRoute = AuthedEquipmentJobsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthedEquipmentJobsRoute,
} as any)
const AuthedEquipmentJobsStockBuildRoute =
  AuthedEquipmentJobsStockBuildRouteImport.update({
    id: '/stock-build',
    path: '/stock-build',
    getParentRoute: () => AuthedEquipmentJobsRoute,
  } as any)
const AuthedEquipmentProductRangesIndexRoute =
  AuthedEquipmentProductRangesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentProductRangesRoute,
  } as any)
const AuthedEquipmentProductsIndexRoute =
  AuthedEquipmentProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentProductsRoute,
  } as any)
const AuthedEquipmentPurchaseOrdersIndexRoute =
  AuthedEquipmentPurchaseOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentPurchaseOrdersRoute,
  } as any)
const AuthedEquipmentPurchaseOrdersIdRoute =
  AuthedEquipmentPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedEquipmentPurchaseOrdersRoute,
  } as any)
const AuthedEquipmentQuotesIndexRoute =
  AuthedEquipmentQuotesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentQuotesRoute,
  } as any)
const AuthedEquipmentSuppliersIndexRoute =
  AuthedEquipmentSuppliersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentSuppliersRoute,
  } as any)
const AuthedEquipmentUnitsIndexRoute =
  AuthedEquipmentUnitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentUnitsRoute,
  } as any)
const AuthedEquipmentUnitsIdRoute = AuthedEquipmentUnitsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedEquipmentUnitsRoute,
} as any)
const AuthedEquipmentCustomersIdEditRoute =
  AuthedEquipmentCustomersIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthedEquipmentCustomersRoute,
  } as any)
const AuthedEquipmentInventoryCloseOutIndexRoute =
  AuthedEquipmentInventoryCloseOutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentInventoryCloseOutRoute,
  } as any)
const AuthedEquipmentInventoryCloseOutJobIdRoute =
  AuthedEquipmentInventoryCloseOutJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthedEquipmentInventoryCloseOutRoute,
  } as any)
const AuthedEquipmentInventoryJobVarianceJobIdRoute =
  AuthedEquipmentInventoryJobVarianceJobIdRouteImport.update({
    id: '/job-variance/$jobId',
    path: '/job-variance/$jobId',
    getParentRoute: () => AuthedEquipmentInventoryRoute,
  } as any)
const AuthedEquipmentInventoryStocktakeIndexRoute =
  AuthedEquipmentInventoryStocktakeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedEquipmentInventoryStocktakeRoute,
  } as any)
const AuthedEquipmentInventoryStocktakeSessionIdRoute =
  AuthedEquipmentInventoryStocktakeSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthedEquipmentInventoryStocktakeRoute,
  } as any)
const AuthedEquipmentProductRangesIdEditRoute =
  AuthedEquipmentProductRangesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthedEquipmentProductRangesRoute,
  } as any)
const AuthedEquipmentProductsIdEditRoute =
  AuthedEquipmentProductsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthedEquipmentProductsRoute,
  } as any)
const AuthedEquipmentQuotesIdEditRoute =
  AuthedEquipmentQuotesIdEditRouteImport.update({
    id: '/$id_/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthedEquipmentQuotesRoute,
  } as any)
const AuthedEquipmentQuotesIdStartJobRoute =
  AuthedEquipmentQuotesIdStartJobRouteImport.update({
    id: '/$id_/start-job',
    path: '/$id/start-job',
    getParentRoute: () => AuthedEquipmentQuotesRoute,
  } as any)
const AuthedEquipmentSuppliersIdEditRoute =
  AuthedEquipmentSuppliersIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthedEquipmentSuppliersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contracting': typeof AuthedContractingRouteWithChildren
  '/equipment': typeof AuthedEquipmentRouteWithChildren
  '/equipment/audit': typeof AuthedEquipmentAuditRoute
  '/equipment/bays': typeof AuthedEquipmentBaysRoute
  '/equipment/catalog-translations': typeof AuthedEquipmentCatalogTranslationsRoute
  '/equipment/customers': typeof AuthedEquipmentCustomersRouteWithChildren
  '/equipment/dashboard': typeof AuthedEquipmentDashboardRoute
  '/equipment/feedback': typeof AuthedEquipmentFeedbackRoute
  '/equipment/inventory': typeof AuthedEquipmentInventoryRouteWithChildren
  '/equipment/jobs': typeof AuthedEquipmentJobsRouteWithChildren
  '/equipment/parts': typeof AuthedEquipmentPartsRoute
  '/equipment/product-ranges': typeof AuthedEquipmentProductRangesRouteWithChildren
  '/equipment/products': typeof AuthedEquipmentProductsRouteWithChildren
  '/equipment/purchase-orders': typeof AuthedEquipmentPurchaseOrdersRouteWithChildren
  '/equipment/quotes': typeof AuthedEquipmentQuotesRouteWithChildren
  '/equipment/suppliers': typeof AuthedEquipmentSuppliersRouteWithChildren
  '/equipment/units': typeof AuthedEquipmentUnitsRouteWithChildren
  '/equipment/users': typeof AuthedEquipmentUsersRoute
  '/contracting/': typeof AuthedContractingIndexRoute
  '/equipment/inventory/$partId': typeof AuthedEquipmentInventoryPartIdRoute
  '/equipment/inventory/buy-list': typeof AuthedEquipmentInventoryBuyListRoute
  '/equipment/inventory/close-out': typeof AuthedEquipmentInventoryCloseOutRouteWithChildren
  '/equipment/inventory/price-variance': typeof AuthedEquipmentInventoryPriceVarianceRoute
  '/equipment/inventory/stocktake': typeof AuthedEquipmentInventoryStocktakeRouteWithChildren
  '/equipment/jobs/$id': typeof AuthedEquipmentJobsIdRoute
  '/equipment/jobs/activity': typeof AuthedEquipmentJobsActivityRoute
  '/equipment/jobs/calendar': typeof AuthedEquipmentJobsCalendarRoute
  '/equipment/jobs/list': typeof AuthedEquipmentJobsListRoute
  '/equipment/jobs/stock-build': typeof AuthedEquipmentJobsStockBuildRoute
  '/equipment/purchase-orders/$id': typeof AuthedEquipmentPurchaseOrdersIdRoute
  '/equipment/units/$id': typeof AuthedEquipmentUnitsIdRoute
  '/equipment/customers/': typeof AuthedEquipmentCustomersIndexRoute
  '/equipment/inventory/': typeof AuthedEquipmentInventoryIndexRoute
  '/equipment/jobs/': typeof AuthedEquipmentJobsIndexRoute
  '/equipment/product-ranges/': typeof AuthedEquipmentProductRangesIndexRoute
  '/equipment/products/': typeof AuthedEquipmentProductsIndexRoute
  '/equipment/purchase-orders/': typeof AuthedEquipmentPurchaseOrdersIndexRoute
  '/equipment/quotes/': typeof AuthedEquipmentQuotesIndexRoute
  '/equipment/suppliers/': typeof AuthedEquipmentSuppliersIndexRoute
  '/equipment/units/': typeof AuthedEquipmentUnitsIndexRoute
  '/equipment/customers/$id/edit': typeof AuthedEquipmentCustomersIdEditRoute
  '/equipment/inventory/close-out/$jobId': typeof AuthedEquipmentInventoryCloseOutJobIdRoute
  '/equipment/inventory/job-variance/$jobId': typeof AuthedEquipmentInventoryJobVarianceJobIdRoute
  '/equipment/inventory/stocktake/$sessionId': typeof AuthedEquipmentInventoryStocktakeSessionIdRoute
  '/equipment/product-ranges/$id/edit': typeof AuthedEquipmentProductRangesIdEditRoute
  '/equipment/products/$id/edit': typeof AuthedEquipmentProductsIdEditRoute
  '/equipment/quotes/$id/edit': typeof AuthedEquipmentQuotesIdEditRoute
  '/equipment/quotes/$id/start-job': typeof AuthedEquipmentQuotesIdStartJobRoute
  '/equipment/suppliers/$id/edit': typeof AuthedEquipmentSuppliersIdEditRoute
  '/equipment/inventory/close-out/': typeof AuthedEquipmentInventoryCloseOutIndexRoute
  '/equipment/inventory/stocktake/': typeof AuthedEquipmentInventoryStocktakeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/verify-email': typeof VerifyEmailRoute
  '/equipment': typeof AuthedEquipmentRouteWithChildren
  '/equipment/audit': typeof AuthedEquipmentAuditRoute
  '/equipment/bays': typeof AuthedEquipmentBaysRoute
  '/equipment/catalog-translations': typeof AuthedEquipmentCatalogTranslationsRoute
  '/equipment/dashboard': typeof AuthedEquipmentDashboardRoute
  '/equipment/feedback': typeof AuthedEquipmentFeedbackRoute
  '/equipment/parts': typeof AuthedEquipmentPartsRoute
  '/equipment/users': typeof AuthedEquipmentUsersRoute
  '/contracting': typeof AuthedContractingIndexRoute
  '/equipment/inventory/$partId': typeof AuthedEquipmentInventoryPartIdRoute
  '/equipment/inventory/buy-list': typeof AuthedEquipmentInventoryBuyListRoute
  '/equipment/inventory/price-variance': typeof AuthedEquipmentInventoryPriceVarianceRoute
  '/equipment/jobs/$id': typeof AuthedEquipmentJobsIdRoute
  '/equipment/jobs/activity': typeof AuthedEquipmentJobsActivityRoute
  '/equipment/jobs/calendar': typeof AuthedEquipmentJobsCalendarRoute
  '/equipment/jobs/list': typeof AuthedEquipmentJobsListRoute
  '/equipment/jobs/stock-build': typeof AuthedEquipmentJobsStockBuildRoute
  '/equipment/purchase-orders/$id': typeof AuthedEquipmentPurchaseOrdersIdRoute
  '/equipment/units/$id': typeof AuthedEquipmentUnitsIdRoute
  '/equipment/customers': typeof AuthedEquipmentCustomersIndexRoute
  '/equipment/inventory': typeof AuthedEquipmentInventoryIndexRoute
  '/equipment/jobs': typeof AuthedEquipmentJobsIndexRoute
  '/equipment/product-ranges': typeof AuthedEquipmentProductRangesIndexRoute
  '/equipment/products': typeof AuthedEquipmentProductsIndexRoute
  '/equipment/purchase-orders': typeof AuthedEquipmentPurchaseOrdersIndexRoute
  '/equipment/quotes': typeof AuthedEquipmentQuotesIndexRoute
  '/equipment/suppliers': typeof AuthedEquipmentSuppliersIndexRoute
  '/equipment/units': typeof AuthedEquipmentUnitsIndexRoute
  '/equipment/customers/$id/edit': typeof AuthedEquipmentCustomersIdEditRoute
  '/equipment/inventory/close-out/$jobId': typeof AuthedEquipmentInventoryCloseOutJobIdRoute
  '/equipment/inventory/job-variance/$jobId': typeof AuthedEquipmentInventoryJobVarianceJobIdRoute
  '/equipment/inventory/stocktake/$sessionId': typeof AuthedEquipmentInventoryStocktakeSessionIdRoute
  '/equipment/product-ranges/$id/edit': typeof AuthedEquipmentProductRangesIdEditRoute
  '/equipment/products/$id/edit': typeof AuthedEquipmentProductsIdEditRoute
  '/equipment/quotes/$id/edit': typeof AuthedEquipmentQuotesIdEditRoute
  '/equipment/quotes/$id/start-job': typeof AuthedEquipmentQuotesIdStartJobRoute
  '/equipment/suppliers/$id/edit': typeof AuthedEquipmentSuppliersIdEditRoute
  '/equipment/inventory/close-out': typeof AuthedEquipmentInventoryCloseOutIndexRoute
  '/equipment/inventory/stocktake': typeof AuthedEquipmentInventoryStocktakeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/contracting': typeof AuthedContractingRouteWithChildren
  '/_authed/equipment': typeof AuthedEquipmentRouteWithChildren
  '/_authed/equipment/audit': typeof AuthedEquipmentAuditRoute
  '/_authed/equipment/bays': typeof AuthedEquipmentBaysRoute
  '/_authed/equipment/catalog-translations': typeof AuthedEquipmentCatalogTranslationsRoute
  '/_authed/equipment/customers': typeof AuthedEquipmentCustomersRouteWithChildren
  '/_authed/equipment/dashboard': typeof AuthedEquipmentDashboardRoute
  '/_authed/equipment/feedback': typeof AuthedEquipmentFeedbackRoute
  '/_authed/equipment/inventory': typeof AuthedEquipmentInventoryRouteWithChildren
  '/_authed/equipment/jobs': typeof AuthedEquipmentJobsRouteWithChildren
  '/_authed/equipment/parts': typeof AuthedEquipmentPartsRoute
  '/_authed/equipment/product-ranges': typeof AuthedEquipmentProductRangesRouteWithChildren
  '/_authed/equipment/products': typeof AuthedEquipmentProductsRouteWithChildren
  '/_authed/equipment/purchase-orders': typeof AuthedEquipmentPurchaseOrdersRouteWithChildren
  '/_authed/equipment/quotes': typeof AuthedEquipmentQuotesRouteWithChildren
  '/_authed/equipment/suppliers': typeof AuthedEquipmentSuppliersRouteWithChildren
  '/_authed/equipment/units': typeof AuthedEquipmentUnitsRouteWithChildren
  '/_authed/equipment/users': typeof AuthedEquipmentUsersRoute
  '/_authed/contracting/': typeof AuthedContractingIndexRoute
  '/_authed/equipment/inventory/$partId': typeof AuthedEquipmentInventoryPartIdRoute
  '/_authed/equipment/inventory/buy-list': typeof AuthedEquipmentInventoryBuyListRoute
  '/_authed/equipment/inventory/close-out': typeof AuthedEquipmentInventoryCloseOutRouteWithChildren
  '/_authed/equipment/inventory/price-variance': typeof AuthedEquipmentInventoryPriceVarianceRoute
  '/_authed/equipment/inventory/stocktake': typeof AuthedEquipmentInventoryStocktakeRouteWithChildren
  '/_authed/equipment/jobs/$id': typeof AuthedEquipmentJobsIdRoute
  '/_authed/equipment/jobs/activity': typeof AuthedEquipmentJobsActivityRoute
  '/_authed/equipment/jobs/calendar': typeof AuthedEquipmentJobsCalendarRoute
  '/_authed/equipment/jobs/list': typeof AuthedEquipmentJobsListRoute
  '/_authed/equipment/jobs/stock-build': typeof AuthedEquipmentJobsStockBuildRoute
  '/_authed/equipment/purchase-orders/$id': typeof AuthedEquipmentPurchaseOrdersIdRoute
  '/_authed/equipment/units/$id': typeof AuthedEquipmentUnitsIdRoute
  '/_authed/equipment/customers/': typeof AuthedEquipmentCustomersIndexRoute
  '/_authed/equipment/inventory/': typeof AuthedEquipmentInventoryIndexRoute
  '/_authed/equipment/jobs/': typeof AuthedEquipmentJobsIndexRoute
  '/_authed/equipment/product-ranges/': typeof AuthedEquipmentProductRangesIndexRoute
  '/_authed/equipment/products/': typeof AuthedEquipmentProductsIndexRoute
  '/_authed/equipment/purchase-orders/': typeof AuthedEquipmentPurchaseOrdersIndexRoute
  '/_authed/equipment/quotes/': typeof AuthedEquipmentQuotesIndexRoute
  '/_authed/equipment/suppliers/': typeof AuthedEquipmentSuppliersIndexRoute
  '/_authed/equipment/units/': typeof AuthedEquipmentUnitsIndexRoute
  '/_authed/equipment/customers/$id/edit': typeof AuthedEquipmentCustomersIdEditRoute
  '/_authed/equipment/inventory/close-out/$jobId': typeof AuthedEquipmentInventoryCloseOutJobIdRoute
  '/_authed/equipment/inventory/job-variance/$jobId': typeof AuthedEquipmentInventoryJobVarianceJobIdRoute
  '/_authed/equipment/inventory/stocktake/$sessionId': typeof AuthedEquipmentInventoryStocktakeSessionIdRoute
  '/_authed/equipment/product-ranges/$id/edit': typeof AuthedEquipmentProductRangesIdEditRoute
  '/_authed/equipment/products/$id/edit': typeof AuthedEquipmentProductsIdEditRoute
  '/_authed/equipment/quotes/$id_/edit': typeof AuthedEquipmentQuotesIdEditRoute
  '/_authed/equipment/quotes/$id_/start-job': typeof AuthedEquipmentQuotesIdStartJobRoute
  '/_authed/equipment/suppliers/$id/edit': typeof AuthedEquipmentSuppliersIdEditRoute
  '/_authed/equipment/inventory/close-out/': typeof AuthedEquipmentInventoryCloseOutIndexRoute
  '/_authed/equipment/inventory/stocktake/': typeof AuthedEquipmentInventoryStocktakeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/support'
    | '/verify-email'
    | '/contracting'
    | '/equipment'
    | '/equipment/audit'
    | '/equipment/bays'
    | '/equipment/catalog-translations'
    | '/equipment/customers'
    | '/equipment/dashboard'
    | '/equipment/feedback'
    | '/equipment/inventory'
    | '/equipment/jobs'
    | '/equipment/parts'
    | '/equipment/product-ranges'
    | '/equipment/products'
    | '/equipment/purchase-orders'
    | '/equipment/quotes'
    | '/equipment/suppliers'
    | '/equipment/units'
    | '/equipment/users'
    | '/contracting/'
    | '/equipment/inventory/$partId'
    | '/equipment/inventory/buy-list'
    | '/equipment/inventory/close-out'
    | '/equipment/inventory/price-variance'
    | '/equipment/inventory/stocktake'
    | '/equipment/jobs/$id'
    | '/equipment/jobs/activity'
    | '/equipment/jobs/calendar'
    | '/equipment/jobs/list'
    | '/equipment/jobs/stock-build'
    | '/equipment/purchase-orders/$id'
    | '/equipment/units/$id'
    | '/equipment/customers/'
    | '/equipment/inventory/'
    | '/equipment/jobs/'
    | '/equipment/product-ranges/'
    | '/equipment/products/'
    | '/equipment/purchase-orders/'
    | '/equipment/quotes/'
    | '/equipment/suppliers/'
    | '/equipment/units/'
    | '/equipment/customers/$id/edit'
    | '/equipment/inventory/close-out/$jobId'
    | '/equipment/inventory/job-variance/$jobId'
    | '/equipment/inventory/stocktake/$sessionId'
    | '/equipment/product-ranges/$id/edit'
    | '/equipment/products/$id/edit'
    | '/equipment/quotes/$id/edit'
    | '/equipment/quotes/$id/start-job'
    | '/equipment/suppliers/$id/edit'
    | '/equipment/inventory/close-out/'
    | '/equipment/inventory/stocktake/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/support'
    | '/verify-email'
    | '/equipment'
    | '/equipment/audit'
    | '/equipment/bays'
    | '/equipment/catalog-translations'
    | '/equipment/dashboard'
    | '/equipment/feedback'
    | '/equipment/parts'
    | '/equipment/users'
    | '/contracting'
    | '/equipment/inventory/$partId'
    | '/equipment/inventory/buy-list'
    | '/equipment/inventory/price-variance'
    | '/equipment/jobs/$id'
    | '/equipment/jobs/activity'
    | '/equipment/jobs/calendar'
    | '/equipment/jobs/list'
    | '/equipment/jobs/stock-build'
    | '/equipment/purchase-orders/$id'
    | '/equipment/units/$id'
    | '/equipment/customers'
    | '/equipment/inventory'
    | '/equipment/jobs'
    | '/equipment/product-ranges'
    | '/equipment/products'
    | '/equipment/purchase-orders'
    | '/equipment/quotes'
    | '/equipment/suppliers'
    | '/equipment/units'
    | '/equipment/customers/$id/edit'
    | '/equipment/inventory/close-out/$jobId'
    | '/equipment/inventory/job-variance/$jobId'
    | '/equipment/inventory/stocktake/$sessionId'
    | '/equipment/product-ranges/$id/edit'
    | '/equipment/products/$id/edit'
    | '/equipment/quotes/$id/edit'
    | '/equipment/quotes/$id/start-job'
    | '/equipment/suppliers/$id/edit'
    | '/equipment/inventory/close-out'
    | '/equipment/inventory/stocktake'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/support'
    | '/verify-email'
    | '/_authed/contracting'
    | '/_authed/equipment'
    | '/_authed/equipment/audit'
    | '/_authed/equipment/bays'
    | '/_authed/equipment/catalog-translations'
    | '/_authed/equipment/customers'
    | '/_authed/equipment/dashboard'
    | '/_authed/equipment/feedback'
    | '/_authed/equipment/inventory'
    | '/_authed/equipment/jobs'
    | '/_authed/equipment/parts'
    | '/_authed/equipment/product-ranges'
    | '/_authed/equipment/products'
    | '/_authed/equipment/purchase-orders'
    | '/_authed/equipment/quotes'
    | '/_authed/equipment/suppliers'
    | '/_authed/equipment/units'
    | '/_authed/equipment/users'
    | '/_authed/contracting/'
    | '/_authed/equipment/inventory/$partId'
    | '/_authed/equipment/inventory/buy-list'
    | '/_authed/equipment/inventory/close-out'
    | '/_authed/equipment/inventory/price-variance'
    | '/_authed/equipment/inventory/stocktake'
    | '/_authed/equipment/jobs/$id'
    | '/_authed/equipment/jobs/activity'
    | '/_authed/equipment/jobs/calendar'
    | '/_authed/equipment/jobs/list'
    | '/_authed/equipment/jobs/stock-build'
    | '/_authed/equipment/purchase-orders/$id'
    | '/_authed/equipment/units/$id'
    | '/_authed/equipment/customers/'
    | '/_authed/equipment/inventory/'
    | '/_authed/equipment/jobs/'
    | '/_authed/equipment/product-ranges/'
    | '/_authed/equipment/products/'
    | '/_authed/equipment/purchase-orders/'
    | '/_authed/equipment/quotes/'
    | '/_authed/equipment/suppliers/'
    | '/_authed/equipment/units/'
    | '/_authed/equipment/customers/$id/edit'
    | '/_authed/equipment/inventory/close-out/$jobId'
    | '/_authed/equipment/inventory/job-variance/$jobId'
    | '/_authed/equipment/inventory/stocktake/$sessionId'
    | '/_authed/equipment/product-ranges/$id/edit'
    | '/_authed/equipment/products/$id/edit'
    | '/_authed/equipment/quotes/$id_/edit'
    | '/_authed/equipment/quotes/$id_/start-job'
    | '/_authed/equipment/suppliers/$id/edit'
    | '/_authed/equipment/inventory/close-out/'
    | '/_authed/equipment/inventory/stocktake/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/contracting': {
      id: '/_authed/contracting'
      path: '/contracting'
      fullPath: '/contracting'
      preLoaderRoute: typeof AuthedContractingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/equipment': {
      id: '/_authed/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthedEquipmentRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contracting/': {
      id: '/_authed/contracting/'
      path: '/'
      fullPath: '/contracting/'
      preLoaderRoute: typeof AuthedContractingIndexRouteImport
      parentRoute: typeof AuthedContractingRoute
    }
    '/_authed/equipment/audit': {
      id: '/_authed/equipment/audit'
      path: '/audit'
      fullPath: '/equipment/audit'
      preLoaderRoute: typeof AuthedEquipmentAuditRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/bays': {
      id: '/_authed/equipment/bays'
      path: '/bays'
      fullPath: '/equipment/bays'
      preLoaderRoute: typeof AuthedEquipmentBaysRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/catalog-translations': {
      id: '/_authed/equipment/catalog-translations'
      path: '/catalog-translations'
      fullPath: '/equipment/catalog-translations'
      preLoaderRoute: typeof AuthedEquipmentCatalogTranslationsRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/customers': {
      id: '/_authed/equipment/customers'
      path: '/customers'
      fullPath: '/equipment/customers'
      preLoaderRoute: typeof AuthedEquipmentCustomersRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/dashboard': {
      id: '/_authed/equipment/dashboard'
      path: '/dashboard'
      fullPath: '/equipment/dashboard'
      preLoaderRoute: typeof AuthedEquipmentDashboardRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/feedback': {
      id: '/_authed/equipment/feedback'
      path: '/feedback'
      fullPath: '/equipment/feedback'
      preLoaderRoute: typeof AuthedEquipmentFeedbackRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/inventory': {
      id: '/_authed/equipment/inventory'
      path: '/inventory'
      fullPath: '/equipment/inventory'
      preLoaderRoute: typeof AuthedEquipmentInventoryRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/jobs': {
      id: '/_authed/equipment/jobs'
      path: '/jobs'
      fullPath: '/equipment/jobs'
      preLoaderRoute: typeof AuthedEquipmentJobsRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/parts': {
      id: '/_authed/equipment/parts'
      path: '/parts'
      fullPath: '/equipment/parts'
      preLoaderRoute: typeof AuthedEquipmentPartsRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/product-ranges': {
      id: '/_authed/equipment/product-ranges'
      path: '/product-ranges'
      fullPath: '/equipment/product-ranges'
      preLoaderRoute: typeof AuthedEquipmentProductRangesRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/products': {
      id: '/_authed/equipment/products'
      path: '/products'
      fullPath: '/equipment/products'
      preLoaderRoute: typeof AuthedEquipmentProductsRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/purchase-orders': {
      id: '/_authed/equipment/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/equipment/purchase-orders'
      preLoaderRoute: typeof AuthedEquipmentPurchaseOrdersRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/quotes': {
      id: '/_authed/equipment/quotes'
      path: '/quotes'
      fullPath: '/equipment/quotes'
      preLoaderRoute: typeof AuthedEquipmentQuotesRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/suppliers': {
      id: '/_authed/equipment/suppliers'
      path: '/suppliers'
      fullPath: '/equipment/suppliers'
      preLoaderRoute: typeof AuthedEquipmentSuppliersRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/units': {
      id: '/_authed/equipment/units'
      path: '/units'
      fullPath: '/equipment/units'
      preLoaderRoute: typeof AuthedEquipmentUnitsRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/users': {
      id: '/_authed/equipment/users'
      path: '/users'
      fullPath: '/equipment/users'
      preLoaderRoute: typeof AuthedEquipmentUsersRouteImport
      parentRoute: typeof AuthedEquipmentRoute
    }
    '/_authed/equipment/customers/': {
      id: '/_authed/equipment/customers/'
      path: '/'
      fullPath: '/equipment/customers/'
      preLoaderRoute: typeof AuthedEquipmentCustomersIndexRouteImport
      parentRoute: typeof AuthedEquipmentCustomersRoute
    }
    '/_authed/equipment/inventory/': {
      id: '/_authed/equipment/inventory/'
      path: '/'
      fullPath: '/equipment/inventory/'
      preLoaderRoute: typeof AuthedEquipmentInventoryIndexRouteImport
      parentRoute: typeof AuthedEquipmentInventoryRoute
    }
    '/_authed/equipment/inventory/$partId': {
      id: '/_authed/equipment/inventory/$partId'
      path: '/$partId'
      fullPath: '/equipment/inventory/$partId'
      preLoaderRoute: typeof AuthedEquipmentInventoryPartIdRouteImport
      parentRoute: typeof AuthedEquipmentInventoryRoute
    }
    '/_authed/equipment/inventory/buy-list': {
      id: '/_authed/equipment/inventory/buy-list'
      path: '/buy-list'
      fullPath: '/equipment/inventory/buy-list'
      preLoaderRoute: typeof AuthedEquipmentInventoryBuyListRouteImport
      parentRoute: typeof AuthedEquipmentInventoryRoute
    }
    '/_authed/equipment/inventory/close-out': {
      id: '/_authed/equipment/inventory/close-out'
      path: '/close-out'
      fullPath: '/equipment/inventory/close-out'
      preLoaderRoute: typeof AuthedEquipmentInventoryCloseOutRouteImport
      parentRoute: typeof AuthedEquipmentInventoryRoute
    }
    '/_authed/equipment/inventory/price-variance': {
      id: '/_authed/equipment/inventory/price-variance'
      path: '/price-variance'
      fullPath: '/equipment/inventory/price-variance'
      preLoaderRoute: typeof AuthedEquipmentInventoryPriceVarianceRouteImport
      parentRoute: typeof AuthedEquipmentInventoryRoute
    }
    '/_authed/equipment/inventory/stocktake': {
      id: '/_authed/equipment/inventory/stocktake'
      path: '/stocktake'
      fullPath: '/equipment/inventory/stocktake'
      preLoaderRoute: typeof AuthedEquipmentInventoryStocktakeRouteImport
      parentRoute: typeof AuthedEquipmentInventoryRoute
    }
    '/_authed/equipment/jobs/': {
      id: '/_authed/equipment/jobs/'
      path: '/'
      fullPath: '/equipment/jobs/'
      preLoaderRoute: typeof AuthedEquipmentJobsIndexRouteImport
      parentRoute: typeof AuthedEquipmentJobsRoute
    }
    '/_authed/equipment/jobs/$id': {
      id: '/_authed/equipment/jobs/$id'
      path: '/$id'
      fullPath: '/equipment/jobs/$id'
      preLoaderRoute: typeof AuthedEquipmentJobsIdRouteImport
      parentRoute: typeof AuthedEquipmentJobsRoute
    }
    '/_authed/equipment/jobs/activity': {
      id: '/_authed/equipment/jobs/activity'
      path: '/activity'
      fullPath: '/equipment/jobs/activity'
      preLoaderRoute: typeof AuthedEquipmentJobsActivityRouteImport
      parentRoute: typeof AuthedEquipmentJobsRoute
    }
    '/_authed/equipment/jobs/calendar': {
      id: '/_authed/equipment/jobs/calendar'
      path: '/calendar'
      fullPath: '/equipment/jobs/calendar'
      preLoaderRoute: typeof AuthedEquipmentJobsCalendarRouteImport
      parentRoute: typeof AuthedEquipmentJobsRoute
    }
    '/_authed/equipment/jobs/list': {
      id: '/_authed/equipment/jobs/list'
      path: '/list'
      fullPath: '/equipment/jobs/list'
      preLoaderRoute: typeof AuthedEquipmentJobsListRouteImport
      parentRoute: typeof AuthedEquipmentJobsRoute
    }
    '/_authed/equipment/jobs/stock-build': {
      id: '/_authed/equipment/jobs/stock-build'
      path: '/stock-build'
      fullPath: '/equipment/jobs/stock-build'
      preLoaderRoute: typeof AuthedEquipmentJobsStockBuildRouteImport
      parentRoute: typeof AuthedEquipmentJobsRoute
    }
    '/_authed/equipment/product-ranges/': {
      id: '/_authed/equipment/product-ranges/'
      path: '/'
      fullPath: '/equipment/product-ranges/'
      preLoaderRoute: typeof AuthedEquipmentProductRangesIndexRouteImport
      parentRoute: typeof AuthedEquipmentProductRangesRoute
    }
    '/_authed/equipment/products/': {
      id: '/_authed/equipment/products/'
      path: '/'
      fullPath: '/equipment/products/'
      preLoaderRoute: typeof AuthedEquipmentProductsIndexRouteImport
      parentRoute: typeof AuthedEquipmentProductsRoute
    }
    '/_authed/equipment/purchase-orders/': {
      id: '/_authed/equipment/purchase-orders/'
      path: '/'
      fullPath: '/equipment/purchase-orders/'
      preLoaderRoute: typeof AuthedEquipmentPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthedEquipmentPurchaseOrdersRoute
    }
    '/_authed/equipment/purchase-orders/$id': {
      id: '/_authed/equipment/purchase-orders/$id'
      path: '/$id'
      fullPath: '/equipment/purchase-orders/$id'
      preLoaderRoute: typeof AuthedEquipmentPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthedEquipmentPurchaseOrdersRoute
    }
    '/_authed/equipment/quotes/': {
      id: '/_authed/equipment/quotes/'
      path: '/'
      fullPath: '/equipment/quotes/'
      preLoaderRoute: typeof AuthedEquipmentQuotesIndexRouteImport
      parentRoute: typeof AuthedEquipmentQuotesRoute
    }
    '/_authed/equipment/suppliers/': {
      id: '/_authed/equipment/suppliers/'
      path: '/'
      fullPath: '/equipment/suppliers/'
      preLoaderRoute: typeof AuthedEquipmentSuppliersIndexRouteImport
      parentRoute: typeof AuthedEquipmentSuppliersRoute
    }
    '/_authed/equipment/units/': {
      id: '/_authed/equipment/units/'
      path: '/'
      fullPath: '/equipment/units/'
      preLoaderRoute: typeof AuthedEquipmentUnitsIndexRouteImport
      parentRoute: typeof AuthedEquipmentUnitsRoute
    }
    '/_authed/equipment/units/$id': {
      id: '/_authed/equipment/units/$id'
      path: '/$id'
      fullPath: '/equipment/units/$id'
      preLoaderRoute: typeof AuthedEquipmentUnitsIdRouteImport
      parentRoute: typeof AuthedEquipmentUnitsRoute
    }
    '/_authed/equipment/customers/$id/edit': {
      id: '/_authed/equipment/customers/$id/edit'
      path: '/$id/edit'
      fullPath: '/equipment/customers/$id/edit'
      preLoaderRoute: typeof AuthedEquipmentCustomersIdEditRouteImport
      parentRoute: typeof AuthedEquipmentCustomersRoute
    }
    '/_authed/equipment/inventory/close-out/': {
      id: '/_authed/equipment/inventory/close-out/'
      path: '/'
      fullPath: '/equipment/inventory/close-out/'
      preLoaderRoute: typeof AuthedEquipmentInventoryCloseOutIndexRouteImport
      parentRoute: typeof AuthedEquipmentInventoryCloseOutRoute
    }
    '/_authed/equipment/inventory/close-out/$jobId': {
      id: '/_authed/equipment/inventory/close-out/$jobId'
      path: '/$jobId'
      fullPath: '/equipment/inventory/close-out/$jobId'
      preLoaderRoute: typeof AuthedEquipmentInventoryCloseOutJobIdRouteImport
      parentRoute: typeof AuthedEquipmentInventoryCloseOutRoute
    }
    '/_authed/equipment/inventory/job-variance/$jobId': {
      id: '/_authed/equipment/inventory/job-variance/$jobId'
      path: '/job-variance/$jobId'
      fullPath: '/equipment/inventory/job-variance/$jobId'
      preLoaderRoute: typeof AuthedEquipmentInventoryJobVarianceJobIdRouteImport
      parentRoute: typeof AuthedEquipmentInventoryRoute
    }
    '/_authed/equipment/inventory/stocktake/': {
      id: '/_authed/equipment/inventory/stocktake/'
      path: '/'
      fullPath: '/equipment/inventory/stocktake/'
      preLoaderRoute: typeof AuthedEquipmentInventoryStocktakeIndexRouteImport
      parentRoute: typeof AuthedEquipmentInventoryStocktakeRoute
    }
    '/_authed/equipment/inventory/stocktake/$sessionId': {
      id: '/_authed/equipment/inventory/stocktake/$sessionId'
      path: '/$sessionId'
      fullPath: '/equipment/inventory/stocktake/$sessionId'
      preLoaderRoute: typeof AuthedEquipmentInventoryStocktakeSessionIdRouteImport
      parentRoute: typeof AuthedEquipmentInventoryStocktakeRoute
    }
    '/_authed/equipment/product-ranges/$id/edit': {
      id: '/_authed/equipment/product-ranges/$id/edit'
      path: '/$id/edit'
      fullPath: '/equipment/product-ranges/$id/edit'
      preLoaderRoute: typeof AuthedEquipmentProductRangesIdEditRouteImport
      parentRoute: typeof AuthedEquipmentProductRangesRoute
    }
    '/_authed/equipment/products/$id/edit': {
      id: '/_authed/equipment/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/equipment/products/$id/edit'
      preLoaderRoute: typeof AuthedEquipmentProductsIdEditRouteImport
      parentRoute: typeof AuthedEquipmentProductsRoute
    }
    '/_authed/equipment/quotes/$id_/edit': {
      id: '/_authed/equipment/quotes/$id_/edit'
      path: '/$id/edit'
      fullPath: '/equipment/quotes/$id/edit'
      preLoaderRoute: typeof AuthedEquipmentQuotesIdEditRouteImport
      parentRoute: typeof AuthedEquipmentQuotesRoute
    }
    '/_authed/equipment/quotes/$id_/start-job': {
      id: '/_authed/equipment/quotes/$id_/start-job'
      path: '/$id/start-job'
      fullPath: '/equipment/quotes/$id/start-job'
      preLoaderRoute: typeof AuthedEquipmentQuotesIdStartJobRouteImport
      parentRoute: typeof AuthedEquipmentQuotesRoute
    }
    '/_authed/equipment/suppliers/$id/edit': {
      id: '/_authed/equipment/suppliers/$id/edit'
      path: '/$id/edit'
      fullPath: '/equipment/suppliers/$id/edit'
      preLoaderRoute: typeof AuthedEquipmentSuppliersIdEditRouteImport
      parentRoute: typeof AuthedEquipmentSuppliersRoute
    }
  }
}

interface AuthedContractingRouteChildren {
  AuthedContractingIndexRoute: typeof AuthedContractingIndexRoute
}

const AuthedContractingRouteChildren: AuthedContractingRouteChildren = {
  AuthedContractingIndexRoute: AuthedContractingIndexRoute,
}

const AuthedContractingRouteWithChildren =
  AuthedContractingRoute._addFileChildren(AuthedContractingRouteChildren)

interface AuthedEquipmentCustomersRouteChildren {
  AuthedEquipmentCustomersIndexRoute: typeof AuthedEquipmentCustomersIndexRoute
  AuthedEquipmentCustomersIdEditRoute: typeof AuthedEquipmentCustomersIdEditRoute
}

const AuthedEquipmentCustomersRouteChildren: AuthedEquipmentCustomersRouteChildren =
  {
    AuthedEquipmentCustomersIndexRoute: AuthedEquipmentCustomersIndexRoute,
    AuthedEquipmentCustomersIdEditRoute: AuthedEquipmentCustomersIdEditRoute,
  }

const AuthedEquipmentCustomersRouteWithChildren =
  AuthedEquipmentCustomersRoute._addFileChildren(
    AuthedEquipmentCustomersRouteChildren,
  )

interface AuthedEquipmentInventoryCloseOutRouteChildren {
  AuthedEquipmentInventoryCloseOutJobIdRoute: typeof AuthedEquipmentInventoryCloseOutJobIdRoute
  AuthedEquipmentInventoryCloseOutIndexRoute: typeof AuthedEquipmentInventoryCloseOutIndexRoute
}

const AuthedEquipmentInventoryCloseOutRouteChildren: AuthedEquipmentInventoryCloseOutRouteChildren =
  {
    AuthedEquipmentInventoryCloseOutJobIdRoute:
      AuthedEquipmentInventoryCloseOutJobIdRoute,
    AuthedEquipmentInventoryCloseOutIndexRoute:
      AuthedEquipmentInventoryCloseOutIndexRoute,
  }

const AuthedEquipmentInventoryCloseOutRouteWithChildren =
  AuthedEquipmentInventoryCloseOutRoute._addFileChildren(
    AuthedEquipmentInventoryCloseOutRouteChildren,
  )

interface AuthedEquipmentInventoryStocktakeRouteChildren {
  AuthedEquipmentInventoryStocktakeSessionIdRoute: typeof AuthedEquipmentInventoryStocktakeSessionIdRoute
  AuthedEquipmentInventoryStocktakeIndexRoute: typeof AuthedEquipmentInventoryStocktakeIndexRoute
}

const AuthedEquipmentInventoryStocktakeRouteChildren: AuthedEquipmentInventoryStocktakeRouteChildren =
  {
    AuthedEquipmentInventoryStocktakeSessionIdRoute:
      AuthedEquipmentInventoryStocktakeSessionIdRoute,
    AuthedEquipmentInventoryStocktakeIndexRoute:
      AuthedEquipmentInventoryStocktakeIndexRoute,
  }

const AuthedEquipmentInventoryStocktakeRouteWithChildren =
  AuthedEquipmentInventoryStocktakeRoute._addFileChildren(
    AuthedEquipmentInventoryStocktakeRouteChildren,
  )

interface AuthedEquipmentInventoryRouteChildren {
  AuthedEquipmentInventoryPartIdRoute: typeof AuthedEquipmentInventoryPartIdRoute
  AuthedEquipmentInventoryBuyListRoute: typeof AuthedEquipmentInventoryBuyListRoute
  AuthedEquipmentInventoryCloseOutRoute: typeof AuthedEquipmentInventoryCloseOutRouteWithChildren
  AuthedEquipmentInventoryPriceVarianceRoute: typeof AuthedEquipmentInventoryPriceVarianceRoute
  AuthedEquipmentInventoryStocktakeRoute: typeof AuthedEquipmentInventoryStocktakeRouteWithChildren
  AuthedEquipmentInventoryIndexRoute: typeof AuthedEquipmentInventoryIndexRoute
  AuthedEquipmentInventoryJobVarianceJobIdRoute: typeof AuthedEquipmentInventoryJobVarianceJobIdRoute
}

const AuthedEquipmentInventoryRouteChildren: AuthedEquipmentInventoryRouteChildren =
  {
    AuthedEquipmentInventoryPartIdRoute: AuthedEquipmentInventoryPartIdRoute,
    AuthedEquipmentInventoryBuyListRoute: AuthedEquipmentInventoryBuyListRoute,
    AuthedEquipmentInventoryCloseOutRoute:
      AuthedEquipmentInventoryCloseOutRouteWithChildren,
    AuthedEquipmentInventoryPriceVarianceRoute:
      AuthedEquipmentInventoryPriceVarianceRoute,
    AuthedEquipmentInventoryStocktakeRoute:
      AuthedEquipmentInventoryStocktakeRouteWithChildren,
    AuthedEquipmentInventoryIndexRoute: AuthedEquipmentInventoryIndexRoute,
    AuthedEquipmentInventoryJobVarianceJobIdRoute:
      AuthedEquipmentInventoryJobVarianceJobIdRoute,
  }

const AuthedEquipmentInventoryRouteWithChildren =
  AuthedEquipmentInventoryRoute._addFileChildren(
    AuthedEquipmentInventoryRouteChildren,
  )

interface AuthedEquipmentJobsRouteChildren {
  AuthedEquipmentJobsIdRoute: typeof AuthedEquipmentJobsIdRoute
  AuthedEquipmentJobsActivityRoute: typeof AuthedEquipmentJobsActivityRoute
  AuthedEquipmentJobsCalendarRoute: typeof AuthedEquipmentJobsCalendarRoute
  AuthedEquipmentJobsListRoute: typeof AuthedEquipmentJobsListRoute
  AuthedEquipmentJobsStockBuildRoute: typeof AuthedEquipmentJobsStockBuildRoute
  AuthedEquipmentJobsIndexRoute: typeof AuthedEquipmentJobsIndexRoute
}

const AuthedEquipmentJobsRouteChildren: AuthedEquipmentJobsRouteChildren = {
  AuthedEquipmentJobsIdRoute: AuthedEquipmentJobsIdRoute,
  AuthedEquipmentJobsActivityRoute: AuthedEquipmentJobsActivityRoute,
  AuthedEquipmentJobsCalendarRoute: AuthedEquipmentJobsCalendarRoute,
  AuthedEquipmentJobsListRoute: AuthedEquipmentJobsListRoute,
  AuthedEquipmentJobsStockBuildRoute: AuthedEquipmentJobsStockBuildRoute,
  AuthedEquipmentJobsIndexRoute: AuthedEquipmentJobsIndexRoute,
}

const AuthedEquipmentJobsRouteWithChildren =
  AuthedEquipmentJobsRoute._addFileChildren(AuthedEquipmentJobsRouteChildren)

interface AuthedEquipmentProductRangesRouteChildren {
  AuthedEquipmentProductRangesIndexRoute: typeof AuthedEquipmentProductRangesIndexRoute
  AuthedEquipmentProductRangesIdEditRoute: typeof AuthedEquipmentProductRangesIdEditRoute
}

const AuthedEquipmentProductRangesRouteChildren: AuthedEquipmentProductRangesRouteChildren =
  {
    AuthedEquipmentProductRangesIndexRoute:
      AuthedEquipmentProductRangesIndexRoute,
    AuthedEquipmentProductRangesIdEditRoute:
      AuthedEquipmentProductRangesIdEditRoute,
  }

const AuthedEquipmentProductRangesRouteWithChildren =
  AuthedEquipmentProductRangesRoute._addFileChildren(
    AuthedEquipmentProductRangesRouteChildren,
  )

interface AuthedEquipmentProductsRouteChildren {
  AuthedEquipmentProductsIndexRoute: typeof AuthedEquipmentProductsIndexRoute
  AuthedEquipmentProductsIdEditRoute: typeof AuthedEquipmentProductsIdEditRoute
}

const AuthedEquipmentProductsRouteChildren: AuthedEquipmentProductsRouteChildren =
  {
    AuthedEquipmentProductsIndexRoute: AuthedEquipmentProductsIndexRoute,
    AuthedEquipmentProductsIdEditRoute: AuthedEquipmentProductsIdEditRoute,
  }

const AuthedEquipmentProductsRouteWithChildren =
  AuthedEquipmentProductsRoute._addFileChildren(
    AuthedEquipmentProductsRouteChildren,
  )

interface AuthedEquipmentPurchaseOrdersRouteChildren {
  AuthedEquipmentPurchaseOrdersIdRoute: typeof AuthedEquipmentPurchaseOrdersIdRoute
  AuthedEquipmentPurchaseOrdersIndexRoute: typeof AuthedEquipmentPurchaseOrdersIndexRoute
}

const AuthedEquipmentPurchaseOrdersRouteChildren: AuthedEquipmentPurchaseOrdersRouteChildren =
  {
    AuthedEquipmentPurchaseOrdersIdRoute: AuthedEquipmentPurchaseOrdersIdRoute,
    AuthedEquipmentPurchaseOrdersIndexRoute:
      AuthedEquipmentPurchaseOrdersIndexRoute,
  }

const AuthedEquipmentPurchaseOrdersRouteWithChildren =
  AuthedEquipmentPurchaseOrdersRoute._addFileChildren(
    AuthedEquipmentPurchaseOrdersRouteChildren,
  )

interface AuthedEquipmentQuotesRouteChildren {
  AuthedEquipmentQuotesIndexRoute: typeof AuthedEquipmentQuotesIndexRoute
  AuthedEquipmentQuotesIdEditRoute: typeof AuthedEquipmentQuotesIdEditRoute
  AuthedEquipmentQuotesIdStartJobRoute: typeof AuthedEquipmentQuotesIdStartJobRoute
}

const AuthedEquipmentQuotesRouteChildren: AuthedEquipmentQuotesRouteChildren = {
  AuthedEquipmentQuotesIndexRoute: AuthedEquipmentQuotesIndexRoute,
  AuthedEquipmentQuotesIdEditRoute: AuthedEquipmentQuotesIdEditRoute,
  AuthedEquipmentQuotesIdStartJobRoute: AuthedEquipmentQuotesIdStartJobRoute,
}

const AuthedEquipmentQuotesRouteWithChildren =
  AuthedEquipmentQuotesRoute._addFileChildren(
    AuthedEquipmentQuotesRouteChildren,
  )

interface AuthedEquipmentSuppliersRouteChildren {
  AuthedEquipmentSuppliersIndexRoute: typeof AuthedEquipmentSuppliersIndexRoute
  AuthedEquipmentSuppliersIdEditRoute: typeof AuthedEquipmentSuppliersIdEditRoute
}

const AuthedEquipmentSuppliersRouteChildren: AuthedEquipmentSuppliersRouteChildren =
  {
    AuthedEquipmentSuppliersIndexRoute: AuthedEquipmentSuppliersIndexRoute,
    AuthedEquipmentSuppliersIdEditRoute: AuthedEquipmentSuppliersIdEditRoute,
  }

const AuthedEquipmentSuppliersRouteWithChildren =
  AuthedEquipmentSuppliersRoute._addFileChildren(
    AuthedEquipmentSuppliersRouteChildren,
  )

interface AuthedEquipmentUnitsRouteChildren {
  AuthedEquipmentUnitsIdRoute: typeof AuthedEquipmentUnitsIdRoute
  AuthedEquipmentUnitsIndexRoute: typeof AuthedEquipmentUnitsIndexRoute
}

const AuthedEquipmentUnitsRouteChildren: AuthedEquipmentUnitsRouteChildren = {
  AuthedEquipmentUnitsIdRoute: AuthedEquipmentUnitsIdRoute,
  AuthedEquipmentUnitsIndexRoute: AuthedEquipmentUnitsIndexRoute,
}

const AuthedEquipmentUnitsRouteWithChildren =
  AuthedEquipmentUnitsRoute._addFileChildren(AuthedEquipmentUnitsRouteChildren)

interface AuthedEquipmentRouteChildren {
  AuthedEquipmentAuditRoute: typeof AuthedEquipmentAuditRoute
  AuthedEquipmentBaysRoute: typeof AuthedEquipmentBaysRoute
  AuthedEquipmentCatalogTranslationsRoute: typeof AuthedEquipmentCatalogTranslationsRoute
  AuthedEquipmentCustomersRoute: typeof AuthedEquipmentCustomersRouteWithChildren
  AuthedEquipmentDashboardRoute: typeof AuthedEquipmentDashboardRoute
  AuthedEquipmentFeedbackRoute: typeof AuthedEquipmentFeedbackRoute
  AuthedEquipmentInventoryRoute: typeof AuthedEquipmentInventoryRouteWithChildren
  AuthedEquipmentJobsRoute: typeof AuthedEquipmentJobsRouteWithChildren
  AuthedEquipmentPartsRoute: typeof AuthedEquipmentPartsRoute
  AuthedEquipmentProductRangesRoute: typeof AuthedEquipmentProductRangesRouteWithChildren
  AuthedEquipmentProductsRoute: typeof AuthedEquipmentProductsRouteWithChildren
  AuthedEquipmentPurchaseOrdersRoute: typeof AuthedEquipmentPurchaseOrdersRouteWithChildren
  AuthedEquipmentQuotesRoute: typeof AuthedEquipmentQuotesRouteWithChildren
  AuthedEquipmentSuppliersRoute: typeof AuthedEquipmentSuppliersRouteWithChildren
  AuthedEquipmentUnitsRoute: typeof AuthedEquipmentUnitsRouteWithChildren
  AuthedEquipmentUsersRoute: typeof AuthedEquipmentUsersRoute
}

const AuthedEquipmentRouteChildren: AuthedEquipmentRouteChildren = {
  AuthedEquipmentAuditRoute: AuthedEquipmentAuditRoute,
  AuthedEquipmentBaysRoute: AuthedEquipmentBaysRoute,
  AuthedEquipmentCatalogTranslationsRoute:
    AuthedEquipmentCatalogTranslationsRoute,
  AuthedEquipmentCustomersRoute: AuthedEquipmentCustomersRouteWithChildren,
  AuthedEquipmentDashboardRoute: AuthedEquipmentDashboardRoute,
  AuthedEquipmentFeedbackRoute: AuthedEquipmentFeedbackRoute,
  AuthedEquipmentInventoryRoute: AuthedEquipmentInventoryRouteWithChildren,
  AuthedEquipmentJobsRoute: AuthedEquipmentJobsRouteWithChildren,
  AuthedEquipmentPartsRoute: AuthedEquipmentPartsRoute,
  AuthedEquipmentProductRangesRoute:
    AuthedEquipmentProductRangesRouteWithChildren,
  AuthedEquipmentProductsRoute: AuthedEquipmentProductsRouteWithChildren,
  AuthedEquipmentPurchaseOrdersRoute:
    AuthedEquipmentPurchaseOrdersRouteWithChildren,
  AuthedEquipmentQuotesRoute: AuthedEquipmentQuotesRouteWithChildren,
  AuthedEquipmentSuppliersRoute: AuthedEquipmentSuppliersRouteWithChildren,
  AuthedEquipmentUnitsRoute: AuthedEquipmentUnitsRouteWithChildren,
  AuthedEquipmentUsersRoute: AuthedEquipmentUsersRoute,
}

const AuthedEquipmentRouteWithChildren = AuthedEquipmentRoute._addFileChildren(
  AuthedEquipmentRouteChildren,
)

interface AuthedRouteChildren {
  AuthedContractingRoute: typeof AuthedContractingRouteWithChildren
  AuthedEquipmentRoute: typeof AuthedEquipmentRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedContractingRoute: AuthedContractingRouteWithChildren,
  AuthedEquipmentRoute: AuthedEquipmentRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
