/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as AuthedRouteImport } from './../routes/_authed'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AuthedUsersRouteImport } from './../routes/_authed.users'
import { Route as AuthedProductsRouteImport } from './../routes/_authed.products'
import { Route as AuthedJobsRouteImport } from './../routes/_authed.jobs'
import { Route as AuthedDashboardRouteImport } from './../routes/_authed.dashboard'
import { Route as AuthedAssistantRouteImport } from './../routes/_authed.assistant'
import { Route as AuthedProductsIndexRouteImport } from './../routes/_authed.products.index'
import { Route as AuthedJobsIndexRouteImport } from './../routes/_authed.jobs.index'
import { Route as AuthedProductsNewRouteImport } from './../routes/_authed.products.new'
import { Route as AuthedJobsIdRouteImport } from './../routes/_authed.jobs.$id'
import { Route as AuthedProductsIdEditRouteImport } from './../routes/_authed.products.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsRoute = AuthedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssistantRoute = AuthedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProductsRoute,
} as any)
const AuthedJobsIndexRoute = AuthedJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedJobsRoute,
} as any)
const AuthedProductsNewRoute = AuthedProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedProductsRoute,
} as any)
const AuthedJobsIdRoute = AuthedJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedJobsRoute,
} as any)
const AuthedProductsIdEditRoute = AuthedProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AuthedProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assistant': typeof AuthedAssistantRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/jobs': typeof AuthedJobsRouteWithChildren
  '/products': typeof AuthedProductsRouteWithChildren
  '/users': typeof AuthedUsersRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/jobs/': typeof AuthedJobsIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/products/$id/edit': typeof AuthedProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assistant': typeof AuthedAssistantRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/users': typeof AuthedUsersRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/jobs': typeof AuthedJobsIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/products/$id/edit': typeof AuthedProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/assistant': typeof AuthedAssistantRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/jobs': typeof AuthedJobsRouteWithChildren
  '/_authed/products': typeof AuthedProductsRouteWithChildren
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/jobs/$id': typeof AuthedJobsIdRoute
  '/_authed/products/new': typeof AuthedProductsNewRoute
  '/_authed/jobs/': typeof AuthedJobsIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/products/$id/edit': typeof AuthedProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assistant'
    | '/dashboard'
    | '/jobs'
    | '/products'
    | '/users'
    | '/jobs/$id'
    | '/products/new'
    | '/jobs/'
    | '/products/'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assistant'
    | '/dashboard'
    | '/users'
    | '/jobs/$id'
    | '/products/new'
    | '/jobs'
    | '/products'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/assistant'
    | '/_authed/dashboard'
    | '/_authed/jobs'
    | '/_authed/products'
    | '/_authed/users'
    | '/_authed/jobs/$id'
    | '/_authed/products/new'
    | '/_authed/jobs/'
    | '/_authed/products/'
    | '/_authed/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs': {
      id: '/_authed/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthedJobsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assistant': {
      id: '/_authed/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthedAssistantRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedProductsRoute
    }
    '/_authed/jobs/': {
      id: '/_authed/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthedJobsIndexRouteImport
      parentRoute: typeof AuthedJobsRoute
    }
    '/_authed/products/new': {
      id: '/_authed/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthedProductsNewRouteImport
      parentRoute: typeof AuthedProductsRoute
    }
    '/_authed/jobs/$id': {
      id: '/_authed/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthedJobsIdRouteImport
      parentRoute: typeof AuthedJobsRoute
    }
    '/_authed/products/$id/edit': {
      id: '/_authed/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AuthedProductsIdEditRouteImport
      parentRoute: typeof AuthedProductsRoute
    }
  }
}

interface AuthedJobsRouteChildren {
  AuthedJobsIdRoute: typeof AuthedJobsIdRoute
  AuthedJobsIndexRoute: typeof AuthedJobsIndexRoute
}

const AuthedJobsRouteChildren: AuthedJobsRouteChildren = {
  AuthedJobsIdRoute: AuthedJobsIdRoute,
  AuthedJobsIndexRoute: AuthedJobsIndexRoute,
}

const AuthedJobsRouteWithChildren = AuthedJobsRoute._addFileChildren(
  AuthedJobsRouteChildren,
)

interface AuthedProductsRouteChildren {
  AuthedProductsNewRoute: typeof AuthedProductsNewRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedProductsIdEditRoute: typeof AuthedProductsIdEditRoute
}

const AuthedProductsRouteChildren: AuthedProductsRouteChildren = {
  AuthedProductsNewRoute: AuthedProductsNewRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedProductsIdEditRoute: AuthedProductsIdEditRoute,
}

const AuthedProductsRouteWithChildren = AuthedProductsRoute._addFileChildren(
  AuthedProductsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAssistantRoute: typeof AuthedAssistantRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedJobsRoute: typeof AuthedJobsRouteWithChildren
  AuthedProductsRoute: typeof AuthedProductsRouteWithChildren
  AuthedUsersRoute: typeof AuthedUsersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAssistantRoute: AuthedAssistantRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedJobsRoute: AuthedJobsRouteWithChildren,
  AuthedProductsRoute: AuthedProductsRouteWithChildren,
  AuthedUsersRoute: AuthedUsersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
