/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as VerifyEmailRouteImport } from './../routes/verify-email'
import { Route as ResetPasswordRouteImport } from './../routes/reset-password'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as ForgotPasswordRouteImport } from './../routes/forgot-password'
import { Route as AuthedRouteImport } from './../routes/_authed'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AuthedUsersRouteImport } from './../routes/_authed.users'
import { Route as AuthedSuppliersRouteImport } from './../routes/_authed.suppliers'
import { Route as AuthedQuotesRouteImport } from './../routes/_authed.quotes'
import { Route as AuthedProductsRouteImport } from './../routes/_authed.products'
import { Route as AuthedPartsRouteImport } from './../routes/_authed.parts'
import { Route as AuthedJobsRouteImport } from './../routes/_authed.jobs'
import { Route as AuthedDashboardRouteImport } from './../routes/_authed.dashboard'
import { Route as AuthedCustomersRouteImport } from './../routes/_authed.customers'
import { Route as AuthedAuditRouteImport } from './../routes/_authed.audit'
import { Route as AuthedAssistantRouteImport } from './../routes/_authed.assistant'
import { Route as AuthedSuppliersIndexRouteImport } from './../routes/_authed.suppliers.index'
import { Route as AuthedQuotesIndexRouteImport } from './../routes/_authed.quotes.index'
import { Route as AuthedProductsIndexRouteImport } from './../routes/_authed.products.index'
import { Route as AuthedPartsIndexRouteImport } from './../routes/_authed.parts.index'
import { Route as AuthedJobsIndexRouteImport } from './../routes/_authed.jobs.index'
import { Route as AuthedCustomersIndexRouteImport } from './../routes/_authed.customers.index'
import { Route as AuthedSuppliersNewRouteImport } from './../routes/_authed.suppliers.new'
import { Route as AuthedQuotesNewRouteImport } from './../routes/_authed.quotes.new'
import { Route as AuthedQuotesIdRouteImport } from './../routes/_authed.quotes.$id'
import { Route as AuthedProductsNewRouteImport } from './../routes/_authed.products.new'
import { Route as AuthedPartsNewRouteImport } from './../routes/_authed.parts.new'
import { Route as AuthedJobsNewRouteImport } from './../routes/_authed.jobs.new'
import { Route as AuthedJobsIdRouteImport } from './../routes/_authed.jobs.$id'
import { Route as AuthedCustomersNewRouteImport } from './../routes/_authed.customers.new'
import { Route as AuthedSuppliersIdEditRouteImport } from './../routes/_authed.suppliers.$id.edit'
import { Route as AuthedQuotesIdEditRouteImport } from './../routes/_authed.quotes.$id_.edit'
import { Route as AuthedProductsIdEditRouteImport } from './../routes/_authed.products.$id.edit'
import { Route as AuthedPartsIdEditRouteImport } from './../routes/_authed.parts.$id.edit'
import { Route as AuthedCustomersIdEditRouteImport } from './../routes/_authed.customers.$id.edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuppliersRoute = AuthedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQuotesRoute = AuthedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPartsRoute = AuthedPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsRoute = AuthedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersRoute = AuthedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssistantRoute = AuthedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSuppliersIndexRoute = AuthedSuppliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSuppliersRoute,
} as any)
const AuthedQuotesIndexRoute = AuthedQuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedQuotesRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProductsRoute,
} as any)
const AuthedPartsIndexRoute = AuthedPartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPartsRoute,
} as any)
const AuthedJobsIndexRoute = AuthedJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedJobsRoute,
} as any)
const AuthedCustomersIndexRoute = AuthedCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCustomersRoute,
} as any)
const AuthedSuppliersNewRoute = AuthedSuppliersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedSuppliersRoute,
} as any)
const AuthedQuotesNewRoute = AuthedQuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedQuotesRoute,
} as any)
const AuthedQuotesIdRoute = AuthedQuotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedQuotesRoute,
} as any)
const AuthedProductsNewRoute = AuthedProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedProductsRoute,
} as any)
const AuthedPartsNewRoute = AuthedPartsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedPartsRoute,
} as any)
const AuthedJobsNewRoute = AuthedJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedJobsRoute,
} as any)
const AuthedJobsIdRoute = AuthedJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedJobsRoute,
} as any)
const AuthedCustomersNewRoute = AuthedCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedCustomersRoute,
} as any)
const AuthedSuppliersIdEditRoute = AuthedSuppliersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AuthedSuppliersRoute,
} as any)
const AuthedQuotesIdEditRoute = AuthedQuotesIdEditRouteImport.update({
  id: '/$id_/edit',
  path: '/$id/edit',
  getParentRoute: () => AuthedQuotesRoute,
} as any)
const AuthedProductsIdEditRoute = AuthedProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AuthedProductsRoute,
} as any)
const AuthedPartsIdEditRoute = AuthedPartsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AuthedPartsRoute,
} as any)
const AuthedCustomersIdEditRoute = AuthedCustomersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AuthedCustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/assistant': typeof AuthedAssistantRoute
  '/audit': typeof AuthedAuditRoute
  '/customers': typeof AuthedCustomersRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/jobs': typeof AuthedJobsRouteWithChildren
  '/parts': typeof AuthedPartsRouteWithChildren
  '/products': typeof AuthedProductsRouteWithChildren
  '/quotes': typeof AuthedQuotesRouteWithChildren
  '/suppliers': typeof AuthedSuppliersRouteWithChildren
  '/users': typeof AuthedUsersRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/parts/new': typeof AuthedPartsNewRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/quotes/$id': typeof AuthedQuotesIdRoute
  '/quotes/new': typeof AuthedQuotesNewRoute
  '/suppliers/new': typeof AuthedSuppliersNewRoute
  '/customers/': typeof AuthedCustomersIndexRoute
  '/jobs/': typeof AuthedJobsIndexRoute
  '/parts/': typeof AuthedPartsIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/quotes/': typeof AuthedQuotesIndexRoute
  '/suppliers/': typeof AuthedSuppliersIndexRoute
  '/customers/$id/edit': typeof AuthedCustomersIdEditRoute
  '/parts/$id/edit': typeof AuthedPartsIdEditRoute
  '/products/$id/edit': typeof AuthedProductsIdEditRoute
  '/quotes/$id/edit': typeof AuthedQuotesIdEditRoute
  '/suppliers/$id/edit': typeof AuthedSuppliersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/assistant': typeof AuthedAssistantRoute
  '/audit': typeof AuthedAuditRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/users': typeof AuthedUsersRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/parts/new': typeof AuthedPartsNewRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/quotes/$id': typeof AuthedQuotesIdRoute
  '/quotes/new': typeof AuthedQuotesNewRoute
  '/suppliers/new': typeof AuthedSuppliersNewRoute
  '/customers': typeof AuthedCustomersIndexRoute
  '/jobs': typeof AuthedJobsIndexRoute
  '/parts': typeof AuthedPartsIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/quotes': typeof AuthedQuotesIndexRoute
  '/suppliers': typeof AuthedSuppliersIndexRoute
  '/customers/$id/edit': typeof AuthedCustomersIdEditRoute
  '/parts/$id/edit': typeof AuthedPartsIdEditRoute
  '/products/$id/edit': typeof AuthedProductsIdEditRoute
  '/quotes/$id/edit': typeof AuthedQuotesIdEditRoute
  '/suppliers/$id/edit': typeof AuthedSuppliersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/assistant': typeof AuthedAssistantRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/customers': typeof AuthedCustomersRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/jobs': typeof AuthedJobsRouteWithChildren
  '/_authed/parts': typeof AuthedPartsRouteWithChildren
  '/_authed/products': typeof AuthedProductsRouteWithChildren
  '/_authed/quotes': typeof AuthedQuotesRouteWithChildren
  '/_authed/suppliers': typeof AuthedSuppliersRouteWithChildren
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/customers/new': typeof AuthedCustomersNewRoute
  '/_authed/jobs/$id': typeof AuthedJobsIdRoute
  '/_authed/jobs/new': typeof AuthedJobsNewRoute
  '/_authed/parts/new': typeof AuthedPartsNewRoute
  '/_authed/products/new': typeof AuthedProductsNewRoute
  '/_authed/quotes/$id': typeof AuthedQuotesIdRoute
  '/_authed/quotes/new': typeof AuthedQuotesNewRoute
  '/_authed/suppliers/new': typeof AuthedSuppliersNewRoute
  '/_authed/customers/': typeof AuthedCustomersIndexRoute
  '/_authed/jobs/': typeof AuthedJobsIndexRoute
  '/_authed/parts/': typeof AuthedPartsIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/quotes/': typeof AuthedQuotesIndexRoute
  '/_authed/suppliers/': typeof AuthedSuppliersIndexRoute
  '/_authed/customers/$id/edit': typeof AuthedCustomersIdEditRoute
  '/_authed/parts/$id/edit': typeof AuthedPartsIdEditRoute
  '/_authed/products/$id/edit': typeof AuthedProductsIdEditRoute
  '/_authed/quotes/$id_/edit': typeof AuthedQuotesIdEditRoute
  '/_authed/suppliers/$id/edit': typeof AuthedSuppliersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/assistant'
    | '/audit'
    | '/customers'
    | '/dashboard'
    | '/jobs'
    | '/parts'
    | '/products'
    | '/quotes'
    | '/suppliers'
    | '/users'
    | '/customers/new'
    | '/jobs/$id'
    | '/jobs/new'
    | '/parts/new'
    | '/products/new'
    | '/quotes/$id'
    | '/quotes/new'
    | '/suppliers/new'
    | '/customers/'
    | '/jobs/'
    | '/parts/'
    | '/products/'
    | '/quotes/'
    | '/suppliers/'
    | '/customers/$id/edit'
    | '/parts/$id/edit'
    | '/products/$id/edit'
    | '/quotes/$id/edit'
    | '/suppliers/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/assistant'
    | '/audit'
    | '/dashboard'
    | '/users'
    | '/customers/new'
    | '/jobs/$id'
    | '/jobs/new'
    | '/parts/new'
    | '/products/new'
    | '/quotes/$id'
    | '/quotes/new'
    | '/suppliers/new'
    | '/customers'
    | '/jobs'
    | '/parts'
    | '/products'
    | '/quotes'
    | '/suppliers'
    | '/customers/$id/edit'
    | '/parts/$id/edit'
    | '/products/$id/edit'
    | '/quotes/$id/edit'
    | '/suppliers/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-email'
    | '/_authed/assistant'
    | '/_authed/audit'
    | '/_authed/customers'
    | '/_authed/dashboard'
    | '/_authed/jobs'
    | '/_authed/parts'
    | '/_authed/products'
    | '/_authed/quotes'
    | '/_authed/suppliers'
    | '/_authed/users'
    | '/_authed/customers/new'
    | '/_authed/jobs/$id'
    | '/_authed/jobs/new'
    | '/_authed/parts/new'
    | '/_authed/products/new'
    | '/_authed/quotes/$id'
    | '/_authed/quotes/new'
    | '/_authed/suppliers/new'
    | '/_authed/customers/'
    | '/_authed/jobs/'
    | '/_authed/parts/'
    | '/_authed/products/'
    | '/_authed/quotes/'
    | '/_authed/suppliers/'
    | '/_authed/customers/$id/edit'
    | '/_authed/parts/$id/edit'
    | '/_authed/products/$id/edit'
    | '/_authed/quotes/$id_/edit'
    | '/_authed/suppliers/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suppliers': {
      id: '/_authed/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthedSuppliersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/quotes': {
      id: '/_authed/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthedQuotesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parts': {
      id: '/_authed/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof AuthedPartsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs': {
      id: '/_authed/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthedJobsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers': {
      id: '/_authed/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedCustomersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assistant': {
      id: '/_authed/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthedAssistantRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/suppliers/': {
      id: '/_authed/suppliers/'
      path: '/'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthedSuppliersIndexRouteImport
      parentRoute: typeof AuthedSuppliersRoute
    }
    '/_authed/quotes/': {
      id: '/_authed/quotes/'
      path: '/'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthedQuotesIndexRouteImport
      parentRoute: typeof AuthedQuotesRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedProductsRoute
    }
    '/_authed/parts/': {
      id: '/_authed/parts/'
      path: '/'
      fullPath: '/parts/'
      preLoaderRoute: typeof AuthedPartsIndexRouteImport
      parentRoute: typeof AuthedPartsRoute
    }
    '/_authed/jobs/': {
      id: '/_authed/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthedJobsIndexRouteImport
      parentRoute: typeof AuthedJobsRoute
    }
    '/_authed/customers/': {
      id: '/_authed/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthedCustomersIndexRouteImport
      parentRoute: typeof AuthedCustomersRoute
    }
    '/_authed/suppliers/new': {
      id: '/_authed/suppliers/new'
      path: '/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AuthedSuppliersNewRouteImport
      parentRoute: typeof AuthedSuppliersRoute
    }
    '/_authed/quotes/new': {
      id: '/_authed/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthedQuotesNewRouteImport
      parentRoute: typeof AuthedQuotesRoute
    }
    '/_authed/quotes/$id': {
      id: '/_authed/quotes/$id'
      path: '/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AuthedQuotesIdRouteImport
      parentRoute: typeof AuthedQuotesRoute
    }
    '/_authed/products/new': {
      id: '/_authed/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthedProductsNewRouteImport
      parentRoute: typeof AuthedProductsRoute
    }
    '/_authed/parts/new': {
      id: '/_authed/parts/new'
      path: '/new'
      fullPath: '/parts/new'
      preLoaderRoute: typeof AuthedPartsNewRouteImport
      parentRoute: typeof AuthedPartsRoute
    }
    '/_authed/jobs/new': {
      id: '/_authed/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthedJobsNewRouteImport
      parentRoute: typeof AuthedJobsRoute
    }
    '/_authed/jobs/$id': {
      id: '/_authed/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthedJobsIdRouteImport
      parentRoute: typeof AuthedJobsRoute
    }
    '/_authed/customers/new': {
      id: '/_authed/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthedCustomersNewRouteImport
      parentRoute: typeof AuthedCustomersRoute
    }
    '/_authed/suppliers/$id/edit': {
      id: '/_authed/suppliers/$id/edit'
      path: '/$id/edit'
      fullPath: '/suppliers/$id/edit'
      preLoaderRoute: typeof AuthedSuppliersIdEditRouteImport
      parentRoute: typeof AuthedSuppliersRoute
    }
    '/_authed/quotes/$id_/edit': {
      id: '/_authed/quotes/$id_/edit'
      path: '/$id/edit'
      fullPath: '/quotes/$id/edit'
      preLoaderRoute: typeof AuthedQuotesIdEditRouteImport
      parentRoute: typeof AuthedQuotesRoute
    }
    '/_authed/products/$id/edit': {
      id: '/_authed/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AuthedProductsIdEditRouteImport
      parentRoute: typeof AuthedProductsRoute
    }
    '/_authed/parts/$id/edit': {
      id: '/_authed/parts/$id/edit'
      path: '/$id/edit'
      fullPath: '/parts/$id/edit'
      preLoaderRoute: typeof AuthedPartsIdEditRouteImport
      parentRoute: typeof AuthedPartsRoute
    }
    '/_authed/customers/$id/edit': {
      id: '/_authed/customers/$id/edit'
      path: '/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof AuthedCustomersIdEditRouteImport
      parentRoute: typeof AuthedCustomersRoute
    }
  }
}

interface AuthedCustomersRouteChildren {
  AuthedCustomersNewRoute: typeof AuthedCustomersNewRoute
  AuthedCustomersIndexRoute: typeof AuthedCustomersIndexRoute
  AuthedCustomersIdEditRoute: typeof AuthedCustomersIdEditRoute
}

const AuthedCustomersRouteChildren: AuthedCustomersRouteChildren = {
  AuthedCustomersNewRoute: AuthedCustomersNewRoute,
  AuthedCustomersIndexRoute: AuthedCustomersIndexRoute,
  AuthedCustomersIdEditRoute: AuthedCustomersIdEditRoute,
}

const AuthedCustomersRouteWithChildren = AuthedCustomersRoute._addFileChildren(
  AuthedCustomersRouteChildren,
)

interface AuthedJobsRouteChildren {
  AuthedJobsIdRoute: typeof AuthedJobsIdRoute
  AuthedJobsNewRoute: typeof AuthedJobsNewRoute
  AuthedJobsIndexRoute: typeof AuthedJobsIndexRoute
}

const AuthedJobsRouteChildren: AuthedJobsRouteChildren = {
  AuthedJobsIdRoute: AuthedJobsIdRoute,
  AuthedJobsNewRoute: AuthedJobsNewRoute,
  AuthedJobsIndexRoute: AuthedJobsIndexRoute,
}

const AuthedJobsRouteWithChildren = AuthedJobsRoute._addFileChildren(
  AuthedJobsRouteChildren,
)

interface AuthedPartsRouteChildren {
  AuthedPartsNewRoute: typeof AuthedPartsNewRoute
  AuthedPartsIndexRoute: typeof AuthedPartsIndexRoute
  AuthedPartsIdEditRoute: typeof AuthedPartsIdEditRoute
}

const AuthedPartsRouteChildren: AuthedPartsRouteChildren = {
  AuthedPartsNewRoute: AuthedPartsNewRoute,
  AuthedPartsIndexRoute: AuthedPartsIndexRoute,
  AuthedPartsIdEditRoute: AuthedPartsIdEditRoute,
}

const AuthedPartsRouteWithChildren = AuthedPartsRoute._addFileChildren(
  AuthedPartsRouteChildren,
)

interface AuthedProductsRouteChildren {
  AuthedProductsNewRoute: typeof AuthedProductsNewRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedProductsIdEditRoute: typeof AuthedProductsIdEditRoute
}

const AuthedProductsRouteChildren: AuthedProductsRouteChildren = {
  AuthedProductsNewRoute: AuthedProductsNewRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedProductsIdEditRoute: AuthedProductsIdEditRoute,
}

const AuthedProductsRouteWithChildren = AuthedProductsRoute._addFileChildren(
  AuthedProductsRouteChildren,
)

interface AuthedQuotesRouteChildren {
  AuthedQuotesIdRoute: typeof AuthedQuotesIdRoute
  AuthedQuotesNewRoute: typeof AuthedQuotesNewRoute
  AuthedQuotesIndexRoute: typeof AuthedQuotesIndexRoute
  AuthedQuotesIdEditRoute: typeof AuthedQuotesIdEditRoute
}

const AuthedQuotesRouteChildren: AuthedQuotesRouteChildren = {
  AuthedQuotesIdRoute: AuthedQuotesIdRoute,
  AuthedQuotesNewRoute: AuthedQuotesNewRoute,
  AuthedQuotesIndexRoute: AuthedQuotesIndexRoute,
  AuthedQuotesIdEditRoute: AuthedQuotesIdEditRoute,
}

const AuthedQuotesRouteWithChildren = AuthedQuotesRoute._addFileChildren(
  AuthedQuotesRouteChildren,
)

interface AuthedSuppliersRouteChildren {
  AuthedSuppliersNewRoute: typeof AuthedSuppliersNewRoute
  AuthedSuppliersIndexRoute: typeof AuthedSuppliersIndexRoute
  AuthedSuppliersIdEditRoute: typeof AuthedSuppliersIdEditRoute
}

const AuthedSuppliersRouteChildren: AuthedSuppliersRouteChildren = {
  AuthedSuppliersNewRoute: AuthedSuppliersNewRoute,
  AuthedSuppliersIndexRoute: AuthedSuppliersIndexRoute,
  AuthedSuppliersIdEditRoute: AuthedSuppliersIdEditRoute,
}

const AuthedSuppliersRouteWithChildren = AuthedSuppliersRoute._addFileChildren(
  AuthedSuppliersRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAssistantRoute: typeof AuthedAssistantRoute
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedCustomersRoute: typeof AuthedCustomersRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedJobsRoute: typeof AuthedJobsRouteWithChildren
  AuthedPartsRoute: typeof AuthedPartsRouteWithChildren
  AuthedProductsRoute: typeof AuthedProductsRouteWithChildren
  AuthedQuotesRoute: typeof AuthedQuotesRouteWithChildren
  AuthedSuppliersRoute: typeof AuthedSuppliersRouteWithChildren
  AuthedUsersRoute: typeof AuthedUsersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAssistantRoute: AuthedAssistantRoute,
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedCustomersRoute: AuthedCustomersRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedJobsRoute: AuthedJobsRouteWithChildren,
  AuthedPartsRoute: AuthedPartsRouteWithChildren,
  AuthedProductsRoute: AuthedProductsRouteWithChildren,
  AuthedQuotesRoute: AuthedQuotesRouteWithChildren,
  AuthedSuppliersRoute: AuthedSuppliersRouteWithChildren,
  AuthedUsersRoute: AuthedUsersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
