/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsModelCodeRouteImport } from './routes/products/$modelCode'
import { Route as ImagesRangesRangeIdRouteImport } from './routes/images/ranges/$rangeId'
import { Route as ImagesProductsProductIdRouteImport } from './routes/images/products/$productId'
import { Route as DownloadsProductsProductIdBrochureRouteImport } from './routes/downloads/products/$productId/brochure'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsModelCodeRoute = ProductsModelCodeRouteImport.update({
  id: '/products/$modelCode',
  path: '/products/$modelCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRangesRangeIdRoute = ImagesRangesRangeIdRouteImport.update({
  id: '/images/ranges/$rangeId',
  path: '/images/ranges/$rangeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesProductsProductIdRoute = ImagesProductsProductIdRouteImport.update({
  id: '/images/products/$productId',
  path: '/images/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsProductsProductIdBrochureRoute =
  DownloadsProductsProductIdBrochureRouteImport.update({
    id: '/downloads/products/$productId/brochure',
    path: '/downloads/products/$productId/brochure',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/products/$modelCode': typeof ProductsModelCodeRoute
  '/products/': typeof ProductsIndexRoute
  '/images/products/$productId': typeof ImagesProductsProductIdRoute
  '/images/ranges/$rangeId': typeof ImagesRangesRangeIdRoute
  '/downloads/products/$productId/brochure': typeof DownloadsProductsProductIdBrochureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/products/$modelCode': typeof ProductsModelCodeRoute
  '/products': typeof ProductsIndexRoute
  '/images/products/$productId': typeof ImagesProductsProductIdRoute
  '/images/ranges/$rangeId': typeof ImagesRangesRangeIdRoute
  '/downloads/products/$productId/brochure': typeof DownloadsProductsProductIdBrochureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/products/$modelCode': typeof ProductsModelCodeRoute
  '/products/': typeof ProductsIndexRoute
  '/images/products/$productId': typeof ImagesProductsProductIdRoute
  '/images/ranges/$rangeId': typeof ImagesRangesRangeIdRoute
  '/downloads/products/$productId/brochure': typeof DownloadsProductsProductIdBrochureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/products/$modelCode'
    | '/products/'
    | '/images/products/$productId'
    | '/images/ranges/$rangeId'
    | '/downloads/products/$productId/brochure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/products/$modelCode'
    | '/products'
    | '/images/products/$productId'
    | '/images/ranges/$rangeId'
    | '/downloads/products/$productId/brochure'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/products/$modelCode'
    | '/products/'
    | '/images/products/$productId'
    | '/images/ranges/$rangeId'
    | '/downloads/products/$productId/brochure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  ProductsModelCodeRoute: typeof ProductsModelCodeRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ImagesProductsProductIdRoute: typeof ImagesProductsProductIdRoute
  ImagesRangesRangeIdRoute: typeof ImagesRangesRangeIdRoute
  DownloadsProductsProductIdBrochureRoute: typeof DownloadsProductsProductIdBrochureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$modelCode': {
      id: '/products/$modelCode'
      path: '/products/$modelCode'
      fullPath: '/products/$modelCode'
      preLoaderRoute: typeof ProductsModelCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/ranges/$rangeId': {
      id: '/images/ranges/$rangeId'
      path: '/images/ranges/$rangeId'
      fullPath: '/images/ranges/$rangeId'
      preLoaderRoute: typeof ImagesRangesRangeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/products/$productId': {
      id: '/images/products/$productId'
      path: '/images/products/$productId'
      fullPath: '/images/products/$productId'
      preLoaderRoute: typeof ImagesProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/products/$productId/brochure': {
      id: '/downloads/products/$productId/brochure'
      path: '/downloads/products/$productId/brochure'
      fullPath: '/downloads/products/$productId/brochure'
      preLoaderRoute: typeof DownloadsProductsProductIdBrochureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  ProductsModelCodeRoute: ProductsModelCodeRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ImagesProductsProductIdRoute: ImagesProductsProductIdRoute,
  ImagesRangesRangeIdRoute: ImagesRangesRangeIdRoute,
  DownloadsProductsProductIdBrochureRoute:
    DownloadsProductsProductIdBrochureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
