/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImagesRangesRangeIdRouteImport } from './routes/images/ranges/$rangeId'
import { Route as ImagesProductsProductIdRouteImport } from './routes/images/products/$productId'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRangesRangeIdRoute = ImagesRangesRangeIdRouteImport.update({
  id: '/images/ranges/$rangeId',
  path: '/images/ranges/$rangeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesProductsProductIdRoute = ImagesProductsProductIdRouteImport.update({
  id: '/images/products/$productId',
  path: '/images/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/images/products/$productId': typeof ImagesProductsProductIdRoute
  '/images/ranges/$rangeId': typeof ImagesRangesRangeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/images/products/$productId': typeof ImagesProductsProductIdRoute
  '/images/ranges/$rangeId': typeof ImagesRangesRangeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/images/products/$productId': typeof ImagesProductsProductIdRoute
  '/images/ranges/$rangeId': typeof ImagesRangesRangeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/images/products/$productId'
    | '/images/ranges/$rangeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/images/products/$productId'
    | '/images/ranges/$rangeId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/images/products/$productId'
    | '/images/ranges/$rangeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  ImagesProductsProductIdRoute: typeof ImagesProductsProductIdRoute
  ImagesRangesRangeIdRoute: typeof ImagesRangesRangeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/ranges/$rangeId': {
      id: '/images/ranges/$rangeId'
      path: '/images/ranges/$rangeId'
      fullPath: '/images/ranges/$rangeId'
      preLoaderRoute: typeof ImagesRangesRangeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/products/$productId': {
      id: '/images/products/$productId'
      path: '/images/products/$productId'
      fullPath: '/images/products/$productId'
      preLoaderRoute: typeof ImagesProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  ImagesProductsProductIdRoute: ImagesProductsProductIdRoute,
  ImagesRangesRangeIdRoute: ImagesRangesRangeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
