/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsModelCodeRouteImport } from './routes/products/$modelCode'
import { Route as InfoSplatRouteImport } from './routes/info/$'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as InfoStaticSplatRouteImport } from './routes/info/static/$'
import { Route as ImagesRangesRangeIdRouteImport } from './routes/images/ranges/$rangeId'
import { Route as ImagesProductsProductIdRouteImport } from './routes/images/products/$productId'
import { Route as DownloadsProductsProductIdBrochureRouteImport } from './routes/downloads/products/$productId/brochure'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsModelCodeRoute = ProductsModelCodeRouteImport.update({
  id: '/products/$modelCode',
  path: '/products/$modelCode',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoSplatRoute = InfoSplatRouteImport.update({
  id: '/info/$',
  path: '/info/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoStaticSplatRoute = InfoStaticSplatRouteImport.update({
  id: '/info/static/$',
  path: '/info/static/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRangesRangeIdRoute = ImagesRangesRangeIdRouteImport.update({
  id: '/images/ranges/$rangeId',
  path: '/images/ranges/$rangeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesProductsProductIdRoute = ImagesProductsProductIdRouteImport.update({
  id: '/images/products/$productId',
  path: '/images/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsProductsProductIdBrochureRoute =
  DownloadsProductsProductIdBrochureRouteImport.update({
    id: '/downloads/products/$productId/brochure',
    path: '/downloads/products/$productId/brochure',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/api/contact': typeof ApiContactRoute
  '/info/$': typeof InfoSplatRoute
  '/products/$modelCode': typeof ProductsModelCodeRoute
  '/products/': typeof ProductsIndexRoute
  '/images/products/$productId': typeof ImagesProductsProductIdRoute
  '/images/ranges/$rangeId': typeof ImagesRangesRangeIdRoute
  '/info/static/$': typeof InfoStaticSplatRoute
  '/downloads/products/$productId/brochure': typeof DownloadsProductsProductIdBrochureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/api/contact': typeof ApiContactRoute
  '/info/$': typeof InfoSplatRoute
  '/products/$modelCode': typeof ProductsModelCodeRoute
  '/products': typeof ProductsIndexRoute
  '/images/products/$productId': typeof ImagesProductsProductIdRoute
  '/images/ranges/$rangeId': typeof ImagesRangesRangeIdRoute
  '/info/static/$': typeof InfoStaticSplatRoute
  '/downloads/products/$productId/brochure': typeof DownloadsProductsProductIdBrochureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/api/contact': typeof ApiContactRoute
  '/info/$': typeof InfoSplatRoute
  '/products/$modelCode': typeof ProductsModelCodeRoute
  '/products/': typeof ProductsIndexRoute
  '/images/products/$productId': typeof ImagesProductsProductIdRoute
  '/images/ranges/$rangeId': typeof ImagesRangesRangeIdRoute
  '/info/static/$': typeof InfoStaticSplatRoute
  '/downloads/products/$productId/brochure': typeof DownloadsProductsProductIdBrochureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/health'
    | '/api/contact'
    | '/info/$'
    | '/products/$modelCode'
    | '/products/'
    | '/images/products/$productId'
    | '/images/ranges/$rangeId'
    | '/info/static/$'
    | '/downloads/products/$productId/brochure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/health'
    | '/api/contact'
    | '/info/$'
    | '/products/$modelCode'
    | '/products'
    | '/images/products/$productId'
    | '/images/ranges/$rangeId'
    | '/info/static/$'
    | '/downloads/products/$productId/brochure'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/health'
    | '/api/contact'
    | '/info/$'
    | '/products/$modelCode'
    | '/products/'
    | '/images/products/$productId'
    | '/images/ranges/$rangeId'
    | '/info/static/$'
    | '/downloads/products/$productId/brochure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HealthRoute: typeof HealthRoute
  ApiContactRoute: typeof ApiContactRoute
  InfoSplatRoute: typeof InfoSplatRoute
  ProductsModelCodeRoute: typeof ProductsModelCodeRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ImagesProductsProductIdRoute: typeof ImagesProductsProductIdRoute
  ImagesRangesRangeIdRoute: typeof ImagesRangesRangeIdRoute
  InfoStaticSplatRoute: typeof InfoStaticSplatRoute
  DownloadsProductsProductIdBrochureRoute: typeof DownloadsProductsProductIdBrochureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$modelCode': {
      id: '/products/$modelCode'
      path: '/products/$modelCode'
      fullPath: '/products/$modelCode'
      preLoaderRoute: typeof ProductsModelCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$': {
      id: '/info/$'
      path: '/info/$'
      fullPath: '/info/$'
      preLoaderRoute: typeof InfoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/static/$': {
      id: '/info/static/$'
      path: '/info/static/$'
      fullPath: '/info/static/$'
      preLoaderRoute: typeof InfoStaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/ranges/$rangeId': {
      id: '/images/ranges/$rangeId'
      path: '/images/ranges/$rangeId'
      fullPath: '/images/ranges/$rangeId'
      preLoaderRoute: typeof ImagesRangesRangeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/products/$productId': {
      id: '/images/products/$productId'
      path: '/images/products/$productId'
      fullPath: '/images/products/$productId'
      preLoaderRoute: typeof ImagesProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/products/$productId/brochure': {
      id: '/downloads/products/$productId/brochure'
      path: '/downloads/products/$productId/brochure'
      fullPath: '/downloads/products/$productId/brochure'
      preLoaderRoute: typeof DownloadsProductsProductIdBrochureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HealthRoute: HealthRoute,
  ApiContactRoute: ApiContactRoute,
  InfoSplatRoute: InfoSplatRoute,
  ProductsModelCodeRoute: ProductsModelCodeRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ImagesProductsProductIdRoute: ImagesProductsProductIdRoute,
  ImagesRangesRangeIdRoute: ImagesRangesRangeIdRoute,
  InfoStaticSplatRoute: InfoStaticSplatRoute,
  DownloadsProductsProductIdBrochureRoute:
    DownloadsProductsProductIdBrochureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
