import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import './load-write-env.js';
import { createDatabaseClient, type DatabaseTransaction, type Db, getDatabaseUrl, sql } from '@pkg/db';
import { hashPassword } from 'better-auth/crypto';
import { assertLocalSeedStorageTarget, assertLocalSeedTarget } from './seed-target-guards.js';
import { deserializeSnapshotRows } from './snapshot-json.js';
import { objectFilePath, snapshotDirectory } from './snapshot-paths.js';
import {
  collectStorageFiles,
  prepareSnapshotRow,
  projectWritableRow,
  type SnapshotRow,
  type SnapshotTableConfig,
  snapshotCleanupTables,
  snapshotTableNames,
  snapshotTables,
} from './snapshot-tables.js';
import { createStorageFromEnv, readSeedStorageConfig, type SeedStorage, uploadObject } from './storage.js';

export type SnapshotWithRows = { config: SnapshotTableConfig; rows: SnapshotRow[] };

type ReplaceSeedSnapshotOptions = {
  clearAllPublicTables?: boolean;
  logPrefix?: string;
};

const insertBatchSize = 500;

// Shared local login for every snapshot-seeded user. Staging password hashes are never dumped (see the
// account config); the seeder fills credential accounts with this on insert so any seeded user can log in.
export const SEED_USER_PASSWORD = 'test123';

async function readSnapshotFile(config: SnapshotTableConfig): Promise<SnapshotRow[]> {
  const snapshotFile = new URL(config.fileName, snapshotDirectory);

  try {
    return deserializeSnapshotRows(config, await readFile(snapshotFile, 'utf8'));
  } catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
      // The snapshot directory is gitignored and regenerated by seed:read. A newly registered table has no
      // file in a snapshot generated before it was added, so treat a missing file as an empty table rather
      // than failing the whole seed — keeps db:seed/parallel:up runnable until the snapshot is regenerated.
      console.warn(`[db:seed] Missing snapshot file ${config.fileName}, seeding 0 rows (run seed:read to populate)`);
      return [];
    }

    throw error;
  }
}

export async function writeLocalSeedSnapshot(database?: Db): Promise<void> {
  const localDatabaseUrl = getDatabaseUrl();
  assertLocalSeedTarget(localDatabaseUrl);

  if (!database) {
    assertLocalSeedStorageTarget(readSeedStorageConfig(''));
  }

  const snapshots = await Promise.all(
    snapshotTables.map(async (config) => ({
      config,
      // Add rollout defaults beneath captured values, then normalize legacy values for the current schema.
      rows: prepareRowsForSeed(config, await readSnapshotFile(config)),
    })),
  );
  const localClient = database ? null : createDatabaseClient(localDatabaseUrl);
  const writableDb = database ?? localClient?.db;

  if (!writableDb) {
    throw new Error('Unable to create local seed database client.');
  }

  try {
    await replaceDatabaseWithSeedSnapshot(writableDb, snapshots);

    // Objects are copied to the local store only when seeding a real local database (not the in-process
    // `database` handle used by tests, which has no doc-store creds). S3 is non-transactional, so this
    // runs after the DB insert transaction commits.
    if (!database) {
      await uploadSnapshotObjects(snapshots);
    }
  } finally {
    await localClient?.close();
  }
}

export function prepareRowsForSeed(config: SnapshotTableConfig, rows: readonly SnapshotRow[]): SnapshotRow[] {
  return rows.map((row, index) => prepareSnapshotRow(config, projectWritableRow(config, row), index));
}

export async function replaceDatabaseWithSeedSnapshot(
  database: Db,
  snapshots: readonly SnapshotWithRows[],
  { clearAllPublicTables = false, logPrefix = 'db:seed' }: ReplaceSeedSnapshotOptions = {},
): Promise<void> {
  const seedPasswordHash = await hashPassword(SEED_USER_PASSWORD);

  await database.transaction(async (tx) => {
    if (clearAllPublicTables) {
      await clearAllPublicTablesForStaging(tx);
    } else {
      await clearSnapshotTables(tx);
    }

    for (const { config, rows } of snapshots) {
      const seedRows = config.seedCredentialPassword ? withSeedPassword(rows, seedPasswordHash) : rows;
      await insertSnapshotRows(tx, config, seedRows);
      await resetSnapshotSequence(tx, config);
      console.info(`[${logPrefix}] Imported ${seedRows.length} ${config.tableName} row(s)`);
    }
  });
}

// Uploads every snapshotted object referenced by the seeded rows into the local doc store, reading the
// bytes downloaded during seed:read. A missing local file is warned about and skipped.
async function uploadSnapshotObjects(snapshots: readonly SnapshotWithRows[]): Promise<void> {
  const storage: SeedStorage = createStorageFromEnv('');

  for (const { config, rows } of snapshots) {
    if (!config.storageFiles) {
      continue;
    }

    let uploaded = 0;

    for (const file of collectStorageFiles(config, rows)) {
      const bytes = await readObjectFile(file.storageKey);

      if (!bytes) {
        console.warn(`[db:seed] Missing local object file ${file.storageKey}, skipping`);
        continue;
      }

      await uploadObject(storage, file.storageKey, bytes, file.contentType);
      uploaded += 1;
    }

    console.info(`[db:seed] Uploaded ${uploaded} ${config.tableName} object(s)`);
  }
}

async function readObjectFile(storageKey: string): Promise<Uint8Array | null> {
  try {
    return await readFile(objectFilePath(storageKey));
  } catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
      return null;
    }

    throw error;
  }
}

// Give every credential account the shared known password so any seeded user can log in locally. The same
// hash is reused across rows — better-auth embeds the salt in the hash, so a single value is sufficient.
function withSeedPassword(rows: readonly SnapshotRow[], passwordHash: string): SnapshotRow[] {
  return rows.map((row) => (row.providerId === 'credential' ? { ...row, password: passwordHash } : row));
}

export async function clearSnapshotTables(tx: DatabaseTransaction): Promise<void> {
  await clearUnsnapshottedPublicTables(tx);

  for (const config of snapshotCleanupTables) {
    await tx.delete(config.table);
  }
}

// A local database also holds rows the snapshot never captures — Purchase Orders, the stock ledger,
// Documents, department stamps — and several of those reference snapshot parents with ON DELETE
// RESTRICT, so leaving them in place fails the next re-seed. Registering each new table here by hand
// only defers the same failure, so the sweep is derived from the catalog: everything in `public` that
// the snapshot does not own is truncated before the ordered snapshot cleanup runs.
async function clearUnsnapshottedPublicTables(tx: DatabaseTransaction): Promise<void> {
  const publicTables = await tx.execute<{ tablename: string }>(
    sql`SELECT tablename FROM pg_tables WHERE schemaname = 'public'`,
  );
  const snapshotted = new Set<string>(snapshotTableNames);
  const tableNames = [...publicTables]
    .map((row) => row.tablename)
    .filter((tableName) => !snapshotted.has(tableName))
    .sort();

  if (tableNames.length === 0) {
    return;
  }

  const identifiers = sql.join(
    tableNames.map((tableName) => sql.identifier(tableName)),
    sql`, `,
  );

  await tx.execute(sql`TRUNCATE TABLE ${identifiers} CASCADE`);
}

async function clearAllPublicTablesForStaging(tx: DatabaseTransaction): Promise<void> {
  // Staging may contain rows in newer/non-snapshotted tables that restrict deletion of snapshot parents.
  // The dynamic list also keeps this destructive path current as new public tables are added.
  await tx.execute(sql`
    DO $$
    DECLARE
      public_tables text;
    BEGIN
      SELECT string_agg(format('%I.%I', schemaname, tablename), ', ')
      INTO public_tables
      FROM pg_tables
      WHERE schemaname = 'public';

      IF public_tables IS NOT NULL THEN
        EXECUTE 'TRUNCATE TABLE ' || public_tables || ' RESTART IDENTITY CASCADE';
      END IF;
    END
    $$;
  `);
}

// Advance a code sequence past the seeded rows so the next app-created row gets a fresh, non-colliding
// code. With rows present, setval(max, true) makes the next nextval return max + 1; with no rows,
// setval(1, false) leaves the next nextval at 1.
async function resetSnapshotSequence(tx: DatabaseTransaction, config: SnapshotTableConfig): Promise<void> {
  if (!config.resetSequence) {
    return;
  }

  const { sequenceName, columnName } = config.resetSequence;

  await tx.execute(
    sql`SELECT setval(${sequenceName}, COALESCE((SELECT MAX(${sql.identifier(columnName)}) FROM ${config.table}), 1), (SELECT COUNT(*) FROM ${config.table}) > 0)`,
  );
}

async function insertSnapshotRows(
  tx: DatabaseTransaction,
  config: SnapshotTableConfig,
  rows: readonly SnapshotRow[],
): Promise<void> {
  for (let index = 0; index < rows.length; index += insertBatchSize) {
    const batch = rows.slice(index, index + insertBatchSize);

    if (batch.length > 0) {
      await tx.insert(config.table).values(batch);
    }
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  await writeLocalSeedSnapshot();
}
