ALTER TABLE "contracting"."job" DROP CONSTRAINT "job_priced_shape";--> statement-breakpoint
ALTER TABLE "contracting"."job" DROP CONSTRAINT "job_diesel_shape";--> statement-breakpoint
ALTER TABLE "contracting"."job" DROP CONSTRAINT "job_discount_shape";--> statement-breakpoint
ALTER TABLE "contracting"."machine_assignment" DROP CONSTRAINT "machine_assignment_pricing_shape";--> statement-breakpoint
ALTER TABLE "contracting"."job" ADD COLUMN "diesel_amount_override" numeric(12, 2);--> statement-breakpoint
ALTER TABLE "contracting"."machine_assignment" ADD COLUMN "amount_override" numeric(12, 2);--> statement-breakpoint
UPDATE "contracting"."machine_assignment"
SET "amount_override" = "final_amount"
WHERE "final_amount" IS NOT NULL AND "computed_amount" IS NOT NULL AND "final_amount" <> "computed_amount";--> statement-breakpoint
UPDATE "contracting"."job"
SET "diesel_amount_override" = "diesel_amount"
WHERE "diesel_amount" IS NOT NULL AND "diesel_unit_price" IS NOT NULL
  AND "diesel_amount"::float8 <> floor("diesel_litres"::float8 * "diesel_unit_price"::float8 * 100 + 0.5) / 100;--> statement-breakpoint
UPDATE "contracting"."machine_assignment" AS "a"
SET "computed_amount" = NULL, "final_amount" = NULL
FROM "contracting"."job" AS "j"
WHERE "j"."id" = "a"."job_id" AND "j"."status" NOT IN ('priced', 'invoiced');--> statement-breakpoint
UPDATE "contracting"."job"
SET "diesel_amount" = NULL, "discount_amount" = NULL
WHERE "status" NOT IN ('priced', 'invoiced');--> statement-breakpoint
ALTER TABLE "contracting"."job" ADD CONSTRAINT "job_priced_shape" CHECK (("contracting"."job"."status" IN ('priced', 'invoiced')) = ("contracting"."job"."priced_at" IS NOT NULL) AND ("contracting"."job"."priced_at" IS NULL) = ("contracting"."job"."priced_subtotal" IS NULL) AND ("contracting"."job"."priced_at" IS NULL) = ("contracting"."job"."priced_total" IS NULL) AND ("contracting"."job"."priced_at" IS NOT NULL OR ("contracting"."job"."diesel_amount" IS NULL AND "contracting"."job"."discount_amount" IS NULL)) AND ("contracting"."job"."priced_at" IS NULL OR "contracting"."job"."diesel_litres" = 0 OR "contracting"."job"."diesel_amount" IS NOT NULL) AND ("contracting"."job"."priced_at" IS NULL OR ("contracting"."job"."discount_kind" IS NULL) = ("contracting"."job"."discount_amount" IS NULL)));--> statement-breakpoint
ALTER TABLE "contracting"."job" ADD CONSTRAINT "job_diesel_shape" CHECK ("contracting"."job"."diesel_litres" >= 0 AND ("contracting"."job"."diesel_unit_price" IS NULL OR "contracting"."job"."diesel_unit_price" >= 0) AND ("contracting"."job"."diesel_amount" IS NULL OR "contracting"."job"."diesel_amount" >= 0) AND ("contracting"."job"."diesel_amount_override" IS NULL OR ("contracting"."job"."diesel_amount_override" >= 0 AND "contracting"."job"."diesel_unit_price" IS NOT NULL)) AND ("contracting"."job"."diesel_amount_override" IS NULL OR "contracting"."job"."diesel_amount" IS NULL OR "contracting"."job"."diesel_amount" = "contracting"."job"."diesel_amount_override"));--> statement-breakpoint
ALTER TABLE "contracting"."job" ADD CONSTRAINT "job_discount_shape" CHECK (("contracting"."job"."discount_kind" IS NULL AND "contracting"."job"."discount_value" IS NULL AND "contracting"."job"."discount_amount" IS NULL) OR ("contracting"."job"."discount_kind" IN ('amount', 'percent') AND "contracting"."job"."discount_value" >= 0 AND ("contracting"."job"."discount_kind" <> 'percent' OR "contracting"."job"."discount_value" <= 100) AND ("contracting"."job"."discount_amount" IS NULL OR "contracting"."job"."discount_amount" >= 0)));--> statement-breakpoint
ALTER TABLE "contracting"."machine_assignment" ADD CONSTRAINT "machine_assignment_pricing_shape" CHECK (("contracting"."machine_assignment"."rate_unit_amount" IS NULL AND "contracting"."machine_assignment"."computed_amount" IS NULL AND "contracting"."machine_assignment"."final_amount" IS NULL AND "contracting"."machine_assignment"."amount_override" IS NULL AND "contracting"."machine_assignment"."rate_name" IS NULL AND "contracting"."machine_assignment"."rate_basis" IS NULL AND "contracting"."machine_assignment"."rate_id" IS NULL AND "contracting"."machine_assignment"."rate_measure_type_id" IS NULL) OR ((("contracting"."machine_assignment"."rate_id" IS NULL AND "contracting"."machine_assignment"."rate_name" IS NULL AND "contracting"."machine_assignment"."rate_unit_amount" = 0 AND "contracting"."machine_assignment"."amount_override" IS NULL) OR ("contracting"."machine_assignment"."rate_id" IS NOT NULL AND length(btrim("contracting"."machine_assignment"."rate_name")) > 0 AND "contracting"."machine_assignment"."rate_basis" IN ('time', 'measure') AND "contracting"."machine_assignment"."rate_unit_amount" > 0 AND ("contracting"."machine_assignment"."amount_override" IS NULL OR "contracting"."machine_assignment"."amount_override" >= 0))) AND ("contracting"."machine_assignment"."computed_amount" IS NULL) = ("contracting"."machine_assignment"."final_amount" IS NULL) AND ("contracting"."machine_assignment"."computed_amount" IS NULL OR ("contracting"."machine_assignment"."computed_amount" >= 0 AND "contracting"."machine_assignment"."final_amount" = COALESCE("contracting"."machine_assignment"."amount_override", "contracting"."machine_assignment"."computed_amount")))));